"""
This type stub file was generated by pyright.
"""

from ..utils import modules_available

def as_buffer(mimetype, array, metadata): # -> memoryview[int] | bytes:
    "Give back a zero-copy memoryview of the array if possible. Otherwise, copy to bytes."
    ...

if modules_available("orjson"):
    ...
def serialize_csv(mimetype, array, metadata): # -> bytes:
    ...

if modules_available("PIL"):
    def save_to_buffer_PIL(mimetype, array, format): # -> memoryview[int]:
        ...
    
    def array_from_buffer_PIL(buffer, format, dtype, shape):
        ...
    
if modules_available("tifffile"):
    def array_from_buffer_tifffile(mimetype, buffer, dtype, shape): # -> ndarray[_AnyShape, dtype[Any]]:
        ...
    
    def save_to_buffer_tifffile(mimetype, array, metadata): # -> memoryview[int]:
        ...
    
def serialize_html(mimetype, array, metadata): # -> str:
    "Try to display as image. Fall back to CSV."
    ...
