"""
This type stub file was generated by pyright.
"""

import awkward
from ..media_type_registration import default_deserialization_registry, default_serialization_registry
from ..structures.core import StructureFamily
from ..utils import APACHE_ARROW_FILE_MIME_TYPE, modules_available

@default_serialization_registry.register(StructureFamily.awkward, "application/zip")
def to_zipped_buffers(mimetype, components, metadata): # -> memoryview[int]:
    ...

@default_deserialization_registry.register(StructureFamily.awkward, "application/zip")
def from_zipped_buffers(buffer, form, length): # -> dict[Any, Any]:
    ...

@default_serialization_registry.register(StructureFamily.awkward, "application/json")
def to_json(mimetype, components, metadata): # -> str:
    ...

if modules_available("pyarrow"):
    @default_serialization_registry.register(StructureFamily.awkward, APACHE_ARROW_FILE_MIME_TYPE)
    def to_arrow(mimetype, components, metadata): # -> memoryview[int]:
        ...
    
    @default_serialization_registry.register(StructureFamily.awkward, "application/x-parquet")
    def to_parquet(mimetype, components, metadata): # -> memoryview[int]:
        ...
    
