"""
This type stub file was generated by pyright.
"""

from ..utils import modules_available

async def walk(node, filter_for_access, pre=...): # -> Generator[Any | tuple[Any | list[Any], Any], Any, None]:
    """
    Yield (key_path, value) where each value is an ArrayAdapter.

    As a succinct illustration (does not literally run):

    >>> list(walk{"a": {"b": 1, "c": {"d": 2}}})
    [
        (("a", "b"), 1),
        (("a", "c", "d"), 2),
    ]
    """
    ...

if modules_available("h5py"):
    async def serialize_hdf5(mimetype, node, metadata, filter_for_access): # -> memoryview[int]:
        """
        Encode everything below this node as HDF5.

        Walk node. Encode all nodes an dataframes as Groups, all arrays and columns as Datasets.
        """
        ...
    
if modules_available("orjson"):
    async def serialize_json(mimetype, node, metadata, filter_for_access): # -> bytes:
        "Export node to JSON, with each node having a 'contents' and 'metadata' sub-key."
        ...
    
