"""
This type stub file was generated by pyright.
"""

"""
The contents of this module are vendored from scikit-image.
"""
_integer_types = ...
_integer_ranges = ...
dtype_range = ...
_supported_types = ...
def img_as_uint(image, force_copy=...): # -> NDArray[Any] | NDArray[numpy.bool[builtins.bool]] | ndarray[_AnyShape, dtype[Any]] | ndarray[tuple[int], dtype[Any]] | _Array[Any | tuple[int], Incomplete]:
    """Convert an image to 16-bit unsigned integer format.
    Parameters
    ----------
    image : ndarray
        Input image.
    force_copy : bool, optional
        Force a copy of the data, irrespective of its current dtype.
    Returns
    -------
    out : ndarray of uint16
        Output image.
    Notes
    -----
    Negative input values will be clipped.
    Positive values are scaled between 0 and 65535.
    """
    ...

def img_as_float(image, force_copy=...): # -> NDArray[Any] | NDArray[numpy.bool[builtins.bool]] | ndarray[_AnyShape, dtype[Any]] | ndarray[tuple[int], dtype[Any]] | _Array[Any | tuple[int], Incomplete]:
    """Convert an image to floating point format.
    This function is similar to `img_as_float64`, but will not convert
    lower-precision floating point arrays to `float64`.
    Parameters
    ----------
    image : ndarray
        Input image.
    force_copy : bool, optional
        Force a copy of the data, irrespective of its current dtype.
    Returns
    -------
    out : ndarray of float
        Output image.
    Notes
    -----
    The range of a floating point image is [0.0, 1.0] or [-1.0, 1.0] when
    converting from unsigned or signed datatypes, respectively.
    If the input image has a float type, intensity values are not modified
    and can be outside the ranges [0.0, 1.0] or [-1.0, 1.0].
    """
    ...

def img_as_ubyte(image, force_copy=...): # -> NDArray[Any] | NDArray[numpy.bool[builtins.bool]] | ndarray[_AnyShape, dtype[Any]] | ndarray[tuple[int], dtype[Any]] | _Array[Any | tuple[int], Incomplete]:
    """Convert an image to 8-bit unsigned integer format.
    Parameters
    ----------
    image : ndarray
        Input image.
    force_copy : bool, optional
        Force a copy of the data, irrespective of its current dtype.
    Returns
    -------
    out : ndarray of ubyte (uint8)
        Output image.
    Notes
    -----
    Negative input values will be clipped.
    Positive values are scaled between 0 and 255.
    """
    ...
