"""
This type stub file was generated by pyright.
"""

from ..utils import modules_available

if modules_available("h5py"):
    def serialize_hdf5(mimetype, sparse_arr, metadata): # -> memoryview[int]:
        """
        Place coords and data in HDF5 datasets with those names.
        """
        ...
    
if modules_available("pandas", "pyarrow"):
    def to_dataframe(sparse_arr): # -> DataFrame:
        ...
    
