"""
This type stub file was generated by pyright.
"""

from ..media_type_registration import default_deserialization_registry, default_serialization_registry
from ..structures.core import StructureFamily
from ..utils import APACHE_ARROW_FILE_MIME_TYPE, XLSX_MIME_TYPE, modules_available

@default_serialization_registry.register(StructureFamily.table, APACHE_ARROW_FILE_MIME_TYPE)
def serialize_arrow(mimetype, df, metadata, preserve_index=...): # -> memoryview[int]:
    ...

@default_deserialization_registry.register(StructureFamily.table, APACHE_ARROW_FILE_MIME_TYPE)
def deserialize_arrow(buffer):
    ...

@default_serialization_registry.register(StructureFamily.table, "application/x-parquet")
def serialize_parquet(mimetype, df, metadata, preserve_index=...): # -> memoryview[int]:
    ...

def serialize_csv(mimetype, df, metadata, preserve_index=...): # -> bytes:
    ...

@default_deserialization_registry.register(StructureFamily.table, "text/csv")
def deserialize_csv(mimetype, buffer): # -> DataFrame:
    ...

@default_serialization_registry.register(StructureFamily.table, "text/html")
def serialize_html(mimetype, df, metadata, preserve_index=...): # -> bytes:
    ...

if modules_available("openpyxl", "pandas"):
    @default_serialization_registry.register(StructureFamily.table, XLSX_MIME_TYPE)
    def serialize_excel(mimetype, df, metadata, preserve_index=...): # -> memoryview[int]:
        ...
    
if modules_available("orjson"):
    @default_serialization_registry.register(StructureFamily.table, "application/json-seq")
    def json_sequence(mimetype, df, metadata): # -> Generator[bytes, Any, None]:
        ...
    
if modules_available("h5py"):
    ...
