"""
This type stub file was generated by pyright.
"""

import io
from ..media_type_registration import default_serialization_registry
from ..utils import modules_available
from .table import APACHE_ARROW_FILE_MIME_TYPE, XLSX_MIME_TYPE

async def as_dataset(node): # -> Dataset:
    ...

class _BytesIOThatIgnoresClose(io.BytesIO):
    def close(self): # -> None:
        ...
    


if modules_available("scipy"):
    @default_serialization_registry.register("xarray_dataset", ["application/netcdf", "application/x-netcdf"])
    async def serialize_netcdf(mimetype, node, metadata, filter_for_access): # -> memoryview[int]:
        ...
    
@default_serialization_registry.register("xarray_dataset", APACHE_ARROW_FILE_MIME_TYPE)
async def serialize_dataset_arrow(mimetype, node, metadata, filter_for_access): # -> memoryview[int]:
    ...

@default_serialization_registry.register("xarray_dataset", "application/x-parquet")
async def serialize_dataset_parquet(mimetype, node, metadata, filter_for_access): # -> memoryview[int]:
    ...

@default_serialization_registry.register("xarray_dataset", ["text/csv", "text/comma-separated-values", "text/plain"])
async def serialize_dataset_csv(mimetype, node, metadata, filter_for_access): # -> bytes:
    ...

@default_serialization_registry.register("xarray_dataset", "text/html")
async def serialize_dataset_html(mimetype, node, metadata, filter_for_access): # -> bytes:
    ...

@default_serialization_registry.register("xarray_dataset", XLSX_MIME_TYPE)
async def serialize_dataset_excel(mimetype, node, metadata, filter_for_access): # -> memoryview[int]:
    ...

if modules_available("orjson"):
    @default_serialization_registry.register("xarray_dataset", "application/json")
    async def serialize_json(mimetype, node, metadata, filter_for_access): # -> bytes:
        ...
    
if modules_available("h5py"):
    @default_serialization_registry.register("xarray_dataset", "application/x-hdf5")
    async def serialize_hdf5(mimetype, node, metadata, filter_for_access): # -> memoryview[int]:
        """
        Like for node, but encode everything under 'attrs' in attrs.
        """
        ...
    
