"""
This type stub file was generated by pyright.
"""

from typing import Callable, Dict, List, Optional, Union
from ..server.settings import DatabaseSettings
from ..utils import Conflicts

logger = ...
DEFAULT_CREATION_MIMETYPE = ...
STORAGE_ADAPTERS_BY_MIMETYPE = ...
class RootNode:
    """
    Node representing the root of the tree.

    This node is special because the state configuring this node arises from
    server initialization (typically a configuration file) not from the
    database.

    It mocks the relevant part of the interface of .orm.Node.
    """
    structure_family = ...
    def __init__(self, metadata, specs, top_level_access_blob) -> None:
        ...
    


class Context:
    def __init__(self, database_settings: DatabaseSettings, writable_storage=..., readable_storage=..., adapters_by_mimetype=..., cache_config=..., key_maker=..., storage_pool_size=..., storage_max_overflow=...) -> None:
        ...
    
    def session(self): # -> ExplainAsyncSession:
        "Convenience method for constructing an AsyncSession context"
        ...
    
    async def execute(self, statement, explain=...): # -> Result[Any]:
        "Debugging convenience utility, not exposed to server"
        ...
    
    async def startup(self): # -> None:
        ...
    
    async def shutdown(self): # -> None:
        ...
    


class CatalogNodeAdapter:
    query_registry = ...
    register_query = ...
    register_query_lazy = ...
    def __init__(self, context, node, *, conditions=..., queries=..., sorting=..., mount_path: Optional[list[str]] = ...) -> None:
        ...
    
    async def path_segments(self):
        ...
    
    @property
    def access_blob(self):
        ...
    
    def metadata(self):
        ...
    
    async def startup(self): # -> None:
        ...
    
    async def create_mount(self, mount_path: list[str]): # -> None:
        ...
    
    async def shutdown(self): # -> None:
        ...
    
    @property
    def writable(self): # -> bool:
        ...
    
    @property
    def key(self):
        ...
    
    def __repr__(self): # -> str:
        ...
    
    async def __aiter__(self):
        ...
    
    @property
    def data_sources(self): # -> list[DataSource[Any]]:
        ...
    
    async def asset_by_id(self, asset_id): # -> Asset | None:
        ...
    
    def structure(self): # -> None:
        ...
    
    def apply_conditions(self, statement):
        ...
    
    async def exact_len(self):
        "Get the exact number of child nodes."
        ...
    
    async def approx_len(self) -> Optional[int]:
        """Get an approximate number of child nodes using table statistics.

        This only works for PostgreSQL databases and does not take into account
        any filtering conditions. To be able to use these queries, the `nodes`
        must be vacuumed and analyzed regularly (at least once).

        If the database is not PostgreSQL, or if the statistics can not be
        obtained, return None.
        """
        ...
    
    async def lbound_len(self, threshold) -> int:
        """Get a fast lower bound on the number of child nodes.

        This only counts up to `threshold`+1 nodes, so is fast even for large
        containers. If result is <= `threshold`, it is exact.
        """
        ...
    
    async def lookup_adapter(self, segments: list[str]): # -> Self | CatalogArrayAdapter | CatalogAwkwardAdapter | CatalogContainerAdapter | CatalogSparseAdapter | CatalogTableAdapter:
        ...
    
    async def get_adapter(self):
        ...
    
    def new_variation(self, *args, sorting=..., conditions=..., queries=..., **kwargs): # -> Self:
        ...
    
    def search(self, query): # -> Self:
        ...
    
    def sort(self, sorting): # -> Self:
        ...
    
    async def get_distinct(self, metadata, structure_families, specs, counts): # -> dict[Any, Any]:
        ...
    
    @property
    def insert(self): # -> Callable[..., sqlalchemy.dialects.sqlite.dml.Insert] | Callable[..., sqlalchemy.dialects.postgresql.dml.Insert]:
        ...
    
    async def create_node(self, structure_family, metadata, key=..., specs=..., data_sources=..., access_blob=...): # -> Self:
        ...
    
    async def put_data_source(self, data_source, patch): # -> None:
        ...
    
    async def revisions(self, offset, limit): # -> list[Revision]:
        ...
    
    async def delete(self, recursive=..., external_only=...): # -> int:
        """Delete the Node, its descendants, and associated DataSources and Assets

        Any DataSources belonging to this Node and any Assets associated (only) with
        those DataSources will also be deleted. Assets shared with other Nodes will
        be retained.

        If `recursive` is True, delete all Nodes beneath this Node in the tree.

        If `external_only` is True, refuse to delete if any internally-managed
        data sources are present in the subtree.

        Parameters
        ----------
        recursive : bool, optional
            Safety check: if False, refuse to delete if the Node has any children.
        external_only : bool, optional
            Safety check: if True, refuse to delete if any internally-managed data
            sources are present in the subtree.

        Returns
        -------
        int
            The number of Asset records deleted.
        """
        ...
    
    async def delete_revision(self, number): # -> None:
        ...
    
    async def replace_metadata(self, metadata=..., specs=..., access_blob=..., *, drop_revision=...): # -> None:
        ...
    
    async def close_stream(self): # -> None:
        ...
    
    def make_ws_handler(self, websocket, formatter, uri):
        ...
    


class CatalogContainerAdapter(CatalogNodeAdapter):
    async def keys_range(self, offset, limit): # -> islice[Any]:
        ...
    
    async def items_range(self, offset, limit): # -> islice[Any] | list[tuple[Any, CatalogArrayAdapter | CatalogAwkwardAdapter | CatalogContainerAdapter | CatalogSparseAdapter | CatalogTableAdapter]]:
        ...
    
    async def read(self, *args, **kwargs): # -> Self:
        ...
    
    def make_ws_schema(self): # -> dict[str, str | int]:
        ...
    


class CatalogArrayAdapter(CatalogNodeAdapter):
    async def read(self, *args, **kwargs): # -> Self:
        ...
    
    async def read_block(self, *args, **kwargs):
        ...
    
    def make_ws_schema(self): # -> dict[str, str | int | dict[str, Any]]:
        ...
    
    async def write(self, media_type, deserializer, entry, body, persist=...): # -> None:
        ...
    
    async def write_block(self, block, media_type, deserializer, entry, body, persist=...): # -> None:
        ...
    
    async def patch(self, shape, offset, extend, media_type, deserializer, entry, body, persist=...):
        ...
    


class CatalogAwkwardAdapter(CatalogNodeAdapter):
    async def read(self, *args, **kwargs):
        ...
    
    async def read_buffers(self, *args, **kwargs):
        ...
    
    async def write(self, *args, **kwargs):
        ...
    


class CatalogSparseAdapter(CatalogArrayAdapter):
    ...


class CatalogTableAdapter(CatalogNodeAdapter):
    def make_ws_schema(self): # -> dict[str, str | int | Any]:
        ...
    
    async def get(self, *args, **kwargs):
        ...
    
    async def read(self, *args, **kwargs):
        ...
    
    async def write(self, media_type, deserializer, entry, body):
        ...
    
    async def read_partition(self, *args, **kwargs):
        ...
    
    async def write_partition(self, media_type, deserializer, entry, body, partition):
        ...
    
    async def append_partition(self, media_type, deserializer, entry, body, partition):
        ...
    


def delete_physical_asset(data_uri, is_directory=..., table_name=..., dataset_id=...): # -> None:
    ...

_STANDARD_SORT_KEYS = ...
def order_by_clauses(sorting): # -> list[Any]:
    ...

_TYPE_CONVERSION_MAP = ...
def binary_op(query, tree, operation):
    ...

def like(query, tree):
    ...

def comparison(query, tree):
    ...

def contains(query, tree):
    ...

def full_text(query, tree):
    ...

def specs(query, tree):
    ...

def access_blob_filter(query, tree):
    ...

def in_or_not_in_sqlite(query, tree, method):
    ...

def in_or_not_in_postgresql(query, tree, method):
    ...

_IN_OR_NOT_IN_DIALECT_DISPATCH: Dict[str, Callable] = ...
def in_or_not_in(query, tree, method):
    ...

def key_present(query, tree):
    ...

def keys_filter(query, tree):
    ...

def structure_family(query, tree):
    ...

def in_memory(*, named_memory=..., metadata=..., specs=..., writable_storage=..., readable_storage=..., adapters_by_mimetype=..., top_level_access_blob=..., cache_config=...): # -> CatalogContainerAdapter:
    ...

def from_uri(uri, *, metadata=..., specs=..., writable_storage=..., readable_storage=..., init_if_not_exists=..., adapters_by_mimetype=..., top_level_access_blob=..., mount_node: Optional[Union[str, List[str]]] = ..., cache_config=..., catalog_pool_size=..., storage_pool_size=..., catalog_max_overflow=..., storage_max_overflow=...): # -> CatalogContainerAdapter:
    ...

def format_distinct_result(results, counts): # -> list[dict[str, Any]]:
    ...

class WouldDeleteData(RuntimeError):
    ...


class Collision(Conflicts):
    ...


def key_array_to_json(keys, value): # -> dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, dict[Any, Any]]]]]]]]]]]]]]]]]]]]]:
    """Take JSON accessor information as an array of keys and value

    Parameters
    ----------
    keys : iterable
        An array of keys to be created in the object.
    value : string
        Value assigned to the final key.

    Returns
    -------
    json
        JSON object for use in postgresql queries.

    Examples
    --------
    >>> key_array_to_json(['x','y','z'], 1)
    {'x': {'y': {'z': 1}}
    """
    ...

def specs_array_to_json(specs): # -> list[dict[str, Any]]:
    """Take array of Specs strings and convert them to a `penguin` @> friendly array
    Assume constructed array will feature keys called "name"

    Parameters
    ----------
    specs : iterable
        An array of specs strings to be searched for.

    Returns
    -------
    json
        JSON object for use in postgresql queries.

    Examples
    --------
    >>> specs_array_to_json(['foo','bar'])
    [{"name":"foo"},{"name":"bar"}]
    """
    ...

def node_from_segments(segments, root_id=...): # -> Select[Tuple[Node]]:
    """Create an SQLAlchemy select statement to find a node based on its path

    Queries the database recursively to find the node with the given ancestors
    and key.

    Parameters
    ----------
        segments : list of str
            The path segments leading to the node, e.g. ['A', 'x', 'i'].
        root_id : int
            The ID of the root node, typically 0 for the root of the catalog.

    Returns
    -------
        sqlalchemy.sql.selectable.Select
    """
    ...

STRUCTURES = ...
class DatabaseInitializationError(Exception):
    ...
