"""
This type stub file was generated by pyright.
"""

import contextlib
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.sql.expression import ClauseElement, Executable

"Adapted from https://github.com/sqlalchemy/sqlalchemy/wiki/Query-Plan-SQL-construct"
EXPLAIN_SQL = ...
class _explain(Executable, ClauseElement):
    inherit_cache = ...
    def __init__(self, stmt, analyze=...) -> None:
        ...
    


@compiles(_explain, "postgresql")
def pg_explain(element, compiler, **kw):
    ...

@compiles(_explain, "sqlite")
def sqlite_explain(element, compiler, **kw):
    ...

_query_explanation_callbacks = ...
@contextlib.contextmanager
def record_explanations(): # -> Generator[list[Any], Any, None]:
    ...

class ExplainAsyncSession(AsyncSession):
    """
    Extend AsyncSession to explain and then query.

    If EXPLAIN_SQL is off and there are now callbacks, just fall back
    to normal AsyncSession. For performance reasons, we only query
    for the explanation if it will be used.

    Use 'explain' paramete (default: None) to force explain on
    or off (True, False).

    1. Explain the query.
    2. Pass the explanation to the callback(s).
    3. Execute normally.
    """
    async def execute(self, statement, *args, explain=..., **kwargs): # -> Result[Any]:
        ...
    
