"""
This type stub file was generated by pyright.
"""

import contextlib
from collections.abc import Generator
from pathlib import Path
from typing import Iterable, Optional
from sqlalchemy.ext.asyncio import AsyncEngine

def write_alembic_ini(alembic_ini_template_path: Path, alembic_dir: Path, path: Path, database_uri: str): # -> None:
    """Write a complete alembic.ini from our template.

    Parameters
    ----------
    alembic_ini_template_path: str
    alembic_dir: str
    path : str
        path to the alembic.ini file that should be written.
    db_url : str
        The SQLAlchemy database url, e.g. `sqlite+aiosqlite:///tiled.sqlite`.
    """
    ...

@contextlib.contextmanager
def temp_alembic_ini(alembic_ini_template_path: Path, alembic_dir: Path, database_uri: str) -> Generator[str]:
    """
    Context manager for temporary alembic configuration file

    Temporarily write an alembic.ini file for use with alembic migration scripts.
    Context manager yields alembic.ini path.

    Parameters
    ----------
    alembic_ini_template_path: str
    alembic_dir: str
    database_uri : str
        The SQLAlchemy database url, e.g. `sqlite+aiosqlite:///tiled.sqlite`.

    Returns
    -------
    alembic_ini: str
        The path to the temporary alembic.ini that we have created.
        This file will be cleaned up on exit from the context manager.
    """
    ...

def stamp_head(alembic_ini_template_path: Path, alembic_dir: Path, engine_url: str): # -> None:
    """
    Upgrade schema to the specified revision.
    """
    ...

def upgrade(alembic_ini_template_path: Path, alembic_dir: Path, engine_url: str, revision: str): # -> None:
    """
    Upgrade schema to the specified revision.
    """
    ...

def downgrade(alembic_ini_template_path: Path, alembic_dir: Path, engine_url: str, revision: str): # -> None:
    """
    Downgrade schema to the specified revision.
    """
    ...

class UnrecognizedDatabase(Exception):
    ...


class UninitializedDatabase(Exception):
    ...


class DatabaseUpgradeNeeded(Exception):
    ...


async def get_current_revision(engine: AsyncEngine, known_revisions: Iterable[str]) -> Optional[str]:
    ...

async def check_database(engine: AsyncEngine, required_revision: str, known_revisions: Iterable[str]): # -> None:
    ...
