"""
This type stub file was generated by pyright.
"""

"""
Iterables for KeysView, ValuesView, ItemsView that are sliceable.
"""
class IterViewBase:
    __slots__ = ...
    def __init__(self, get_length) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def first(self):
        ...
    
    def last(self):
        ...
    
    def head(self, n=...):
        ...
    
    def tail(self, n=...): # -> list[Any]:
        ...
    
    def __init_subclass__(cls, *args, **kwargs): # -> None:
        ...
    
    def __len__(self):
        ...
    


class KeysView(IterViewBase):
    """
    A sliceable, iterable view of keys.
    """
    __slots__ = ...
    _name = ...
    def __init__(self, get_length, keys_slice, page_size=...) -> None:
        ...
    
    def page_size(self, n): # -> Self:
        "Set page size, to tune performance."
        ...
    
    def __getitem__(self, index_or_slice): # -> list[Any]:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    


class ItemsView(IterViewBase):
    """
    A sliceable, iterable view of (key, value) pairs.
    """
    __slots__ = ...
    _name = ...
    def __init__(self, get_length, items_slice, page_size=...) -> None:
        ...
    
    def page_size(self, n): # -> Self:
        "Set page size, to tune performance."
        ...
    
    def __getitem__(self, index_or_slice): # -> list[Any]:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    


class ValuesView(IterViewBase):
    """
    A sliceable, iterable view of values.
    """
    __slots__ = ...
    _name = ...
    def __init__(self, get_length, items_slice, page_size=...) -> None:
        ...
    
    def page_size(self, n): # -> Self:
        "Set page size, to tune performance."
        ...
    
    def __getitem__(self, index_or_slice): # -> list[Any]:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    


def slice_to_interval(slice_): # -> tuple[Any | int, Any, Literal[1, -1]]:
    """
    Convert slice object to (start, stop, direction).
    """
    ...
