"""
This type stub file was generated by pyright.
"""

"""
Generate the 'links' section of the response JSON.

The links vary by structure family.
"""
def links_for_node(structure_family, structure, base_url, path_str): # -> dict[Any, Any]:
    ...

def links_for_array(structure_family, structure, base_url, path_str): # -> dict[Any, Any]:
    ...

def links_for_awkward(structure_family, structure, base_url, path_str): # -> dict[Any, Any]:
    ...

def links_for_container(structure_family, structure, base_url, path_str): # -> dict[Any, Any]:
    ...

def links_for_table(structure_family, structure, base_url, path_str): # -> dict[Any, Any]:
    ...

LINKS_BY_STRUCTURE_FAMILY = ...
