"""
This type stub file was generated by pyright.
"""

from .utils import DictView, modules_available

class SerializationRegistry:
    """
    Registry of media types for each structure family

    Examples
    --------

    Register a JSON writer for "array" structures.
    (This is included by default but it is shown here as a simple example.)

    >>> import json
    >>>> serialization_registry.register(
        "array", "application/json", lambda array: json.dumps(array.tolist()).encode()
    )

    """
    DEFAULT_ALIASES = ...
    def __init__(self) -> None:
        ...
    
    def media_types(self, structure_family) -> DictView[str, str]:
        """
        List the supported media types for a given structure family.
        """
        ...
    
    @property
    def structure_families(self): # -> list[Any]:
        """
        List the known structure families.
        """
        ...
    
    def aliases(self, structure_family): # -> dict[Any, Any]:
        """
        List the aliases (file extensions) for each media type for a given structure family.
        """
        ...
    
    def register(self, structure_family, media_type, func=...): # -> Callable[..., Any]:
        """
        Register a new media_type for a structure family.

        Parameters
        ----------
        structure_family : str
            The structure we are encoding, as in "array", "dataframe", "variable", ...
        media_type : {str, List[str]}
            MIME type, as in "application/json" or "text/csv".
            If there is not standard name, use "application/x-INVENT-NAME-HERE".
        func : callable, optional
            Should accept the relevant structure as input (e.g. a numpy array)
            and return bytes or memoryview

        Examples
        --------
        Use as a normal method.

        >>> serialization_registry.register("array", "image/tiff", serialize_tiff)

        Use as a decorator.

        >>> @serialization_registry.register("array", "image_tiff")
        ... def serialize_tiff(...):
        ...     ...
        ...

        """
        ...
    
    def register_alias(self, ext, media_type): # -> None:
        ...
    
    def resolve_alias(self, alias): # -> str:
        ...
    
    def dispatch(self, structure_family, media_type):
        """
        Look up a writer for a given structure and media type.
        """
        ...
    


class CompressionRegistry:
    def __init__(self) -> None:
        ...
    
    def encodings(self, media_type): # -> Iterator[Any]:
        ...
    
    def register(self, media_type, encoding, func): # -> None:
        """
        Register a new media_type for a structure family.

        Parameters
        ----------
        structure_family : str
            The structure we are encoding, as in "array", "dataframe", "variable", ...
        media_type : str
            MIME type, as in "application/json" or "text/csv".
            If there is not standard name, use "application/x-INVENT-NAME-HERE".
        func : callable
            Should accept the relevant structure as input (e.g. a numpy array)
            and return bytes or memoryview
        """
        ...
    
    def dispatch(self, media_type, encoding):
        ...
    
    def __call__(self, media_type, encoder, *args, **kwargs):
        """
        Invoke an encoder.
        """
        ...
    


default_serialization_registry = ...
default_deserialization_registry = ...
default_compression_registry = ...
if modules_available("zstandard"):
    zstd_compressor = ...
    class ZstdBuffer:
        """
        Imitate the API provided by gzip.GzipFile and used by tiled.server.compression.

        It's not clear to me yet what this buys us, but I think we should follow
        the pattern set by starlette until we have a clear reason not to.
        """
        def __init__(self, file) -> None:
            ...
        
        def write(self, b): # -> None:
            ...
        
        def close(self): # -> None:
            ...
        
    
    
if modules_available("lz4"):
    lz4_compress = ...
    class LZ4Buffer:
        """
        Imitate the API provided by gzip.GzipFile and used by tiled.server.compression.

        It's not clear to me yet what this buys us, but I think we should follow
        the pattern set by starlette until we have a clear reason not to.
        """
        def __init__(self, file) -> None:
            ...
        
        def write(self, b): # -> None:
            ...
        
        def close(self): # -> None:
            ...
        
    
    
if modules_available("blosc2"):
    class BloscBuffer:
        """
        Imitate the API provided by gzip.GzipFile and used by tiled.server.compression.

        It's not clear to me yet what this buys us, but I think we should follow
        the pattern set by starlette until we have a clear reason not to.
        """
        def __init__(self, file) -> None:
            ...
        
        def write(self, b): # -> None:
            ...
        
        def close(self): # -> None:
            ...
        
    
    
