"""
This type stub file was generated by pyright.
"""

import builtins
from typing import Optional, Union
from .type_aliases import EllipsisType, JSON

DIM_REGEX = ...
SLICE_REGEX = ...
class NDSlice(tuple):
    """A representation of a slice for N-dimensional arrays.

    This class is a tuple of integers, slices, and Ellipsis objects. It is used to
    represent a slice of an N-dimensional array, similar to how numpy uses slices.

    It also provides methods to convert to and from JSON and numpy-style string
    representations of slices. To encode Ellipsis in JSON, it is represented as
    {"step": 0}, which is not a valid builtin.slice.
    """
    def __new__(cls, *args: Union[int, builtins.slice, EllipsisType]) -> NDSlice:
        ...
    
    def __bool__(self) -> bool:
        "NDSlice is considered empty if all slices are '...' or ':', i.e. returning entire array"
        ...
    
    @classmethod
    def from_json(cls, ser: list[JSON]) -> NDSlice:
        "Deserialize a json representation of an NDSlice"
        ...
    
    def to_json(self, ndim: Optional[int] = ...) -> list[JSON]:
        "Convert NDSlice into a JSON-serializable representation"
        ...
    
    @classmethod
    def from_numpy_str(cls, arg: str) -> NDSlice:
        """Parse and convert a numpy-style string representation of a slice

        For example, '(1:3, 4, 1:5:2, ...)' is converted to (slice(1, 3), 4, slice(1, 5, 2), ...).
        """
        ...
    
    @classmethod
    def from_query(cls, slice: str = ...) -> NDSlice:
        """Parse and convert a query parameter representation of a slice"""
        ...
    
    def to_numpy_str(self) -> str:
        "Convert NDSlice to a numpy-style string representation"
        ...
    
