"""
This type stub file was generated by pyright.
"""

from functools import cache

"""
This module handles client configuration.

See config.py for server configuration.

It contains several functions that are factored to facilitate testing,
but the user-facing functionality is straightforward.
"""
TILED_CACHE_DIR = ...
__all__ = ["list_profiles", "load_profiles", "paths", "create_profile", "delete_profile", "set_default_profile_name", "get_default_profile_name"]
@cache
def schema(): # -> Any:
    "Load the schema for profiles."
    ...

_all_paths = ...
_seen = ...
paths = ...
def gather_profiles(paths, strict=...): # -> list[Any]:
    """
    For each path in paths, return a dict mapping filepath to content.
    """
    ...

def resolve_precedence(levels): # -> dict[Any, Any]:
    """
    Given a list of mappings (filename-to-content), resolve precedence.

    In the event of irresolvable collisions, drop the offenders and warn.

    The result is a mapping from profile name to (filepath, content).
    """
    ...

@cache
def load_profiles(): # -> dict[Any, Any]:
    """
    Return a mapping of profile_name to (source_path, content).

    The files are only actually read the first time this is called.
    Thereafter, the results are cached. To clear the cache and re-read,
    use load_profiles.cache_clear().

    The search path for the source files is available from Python as:

    >>> tiled.client.profiles.paths

    or from a CLI as:

    $ tiled profile paths

    See also

    $ tiled profile list
    $ tiled profile show PROFILE_NAME
    """
    ...

def list_profiles(): # -> dict[Any, Any]:
    """
    Return a mapping of profile names to source filepath.

    The search path for the source files is available from Python as:

    >>> tiled.client.profiles.paths

    or from a CLI as:

    $ tiled profile paths

    See also

    $ tiled profile list
    $ tiled profile show PROFILE_NAME
    """
    ...

def create_profile(uri, name, verify=..., overwrite=...): # -> Path:
    """
    Create a new profile.

    This only includes the most commonly-used options. (More could be added.)
    """
    ...

def delete_profile(name): # -> Path | None:
    """
    Delete a profile by name.

    This will walk the search path, starting with the highest precedence
    directory, and delete only the first match it finds.
    """
    ...

def get_default_profile_name(): # -> str | None:
    """
    Return the name of the current default profile.
    """
    ...

def set_default_profile_name(name): # -> None:
    ...

class ProfileNotFound(KeyError):
    ...


class ProfileError(ValueError):
    ...


class ProfileExists(ValueError):
    ...
