"""
This type stub file was generated by pyright.
"""

from typing import Any
from .utils import DictView

"""
These objects express high-level queries and translate them (when possible)
into concrete queries for specific storage backends.

This intentionally only uses built-in dataclasses, not pydantic models.
"""
class QueryRegistry:
    """
    Keep track of all known queries types, with names.

    When the server starts up, it uses this registry to populate the list of
    allowed URL query parameters to its /search route.

    There is a global instance of this, defined below. It is implemented as a
    class, rather than a module-scope singleton, for the sake of tests.
    """
    def __init__(self) -> None:
        ...
    
    @property
    def name_to_query_type(self) -> DictView[Any, Any]:
        ...
    
    @property
    def query_type_to_name(self) -> DictView[Any, Any]:
        ...
    
    def register(self, name=..., overwrite=..., must_revalidate=...): # -> Callable[..., Any | None]:
        """
        Register a new type of query.
        """
        ...
    


default_query_registry = ...
register = ...
class QueryTranslationRegistry:
    def __init__(self) -> None:
        ...
    
    def register(self, class_, translator) -> Any:
        ...
    
    def register_lazy(self, toplevel, register): # -> None:
        """
        Register a registration function which will be called if the
        *toplevel* module (e.g. 'pandas') is ever loaded.
        """
        ...
    
    def dispatch(self, class_):
        """Return the function implementation for the given ``class_``"""
        ...
    
    def __call__(self, arg, *args, **kwargs):
        """
        Call the corresponding method based on type of argument.
        """
        ...
    
