"""
This type stub file was generated by pyright.
"""

import enum
from dataclasses import dataclass
from typing import Any, List, Optional
from .query_registration import register
from .structures.core import StructureFamily as StructureFamilyEnum

"""
These objects describe queries, independent of how the actual querying is implemented.
They are used on the client side and the server side.

The are encoded into and decoded from URL query parameters.
"""
JSONSerializable = Any
class NoBool:
    def __bool__(self):
        ...
    


@register(name="fulltext")
@dataclass
class FullText(NoBool):
    """
    Search the full text of all metadata values for word matches.

    This matches *complete words*, so 'dog' would match 'cat dog elephant',
    but 'do' would not match.

    Parameters
    ----------
    text : str
    """
    text: str
    def encode(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def decode(cls, *, text): # -> Self:
        ...
    


@register(name="lookup")
@dataclass
class KeyLookup(NoBool):
    """
    Match a specific Entry by key. Mostly for internal use.

    This is necessary to support item lookup within search results, as in:

    >>> tree.search(...)["..."]

    The server handles this directly and generically, simply calling __getitem__
    on the tree after apply all other queries.  Implementations of search(...)
    do not need to handle it.

    Parameters
    ----------
    key : str
    """
    key: str
    def encode(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def decode(cls, *, key): # -> Self:
        ...
    


@register(name="keys_filter")
@dataclass
class KeysFilter(NoBool):
    """
    Filter entries that do not match one of these keys.

    Parameters
    ----------
    keys : List[str]
    """
    keys: List[str]
    def encode(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def decode(cls, *, keys): # -> Self:
        ...
    


@register(name="regex")
@dataclass
class Regex(NoBool):
    """
    Match a key's value to a regular expression.

    Parameters
    ----------
    key : str
        e.g. "color", "sample.name"
    pattern : str
        regular expression
    case_sensitive : bool, optional
        Default True (case-sensitive).
        Note that this is the opposite of the default for FullText;
        regex users generally expect case sensitivity by default.

    Examples
    --------

    Search for color == "red"

    >>> c.search(Regex("sample.name", "Cu.*"))
    """
    key: str
    pattern: str
    case_sensitive: bool = ...
    def encode(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def decode(cls, *, key, pattern, case_sensitive=...): # -> Self:
        ...
    


@register(name="eq")
@dataclass
class Eq(NoBool):
    """
    Query equality of a given key's value to the specified value.

    See `Key` in this module for a more intuitive interface for equality.

    Parameters
    ----------
    key : str
        e.g. "color", "sample.name"
    value : JSONSerializable
        May be a string, number, list, or dict.

    Examples
    --------

    Search for color == "red"

    >>> c.search(Eq("color", "red"))
    """
    key: str
    value: JSONSerializable
    def encode(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def decode(cls, *, key, value): # -> Self:
        ...
    


@register(name="noteq")
@dataclass
class NotEq(NoBool):
    """
    Query inequality of a given key's value to the specified value.

    See `Key` in this module for a more intuitive interface for inequality.

    Parameters
    ----------
    key : str
        e.g. "color", "sample.name"
    value : JSONSerializable
        May be a string, number, list, or dict.

    Examples
    --------

    Search for color == "red"

    >>> c.search(Eq("color", "red"))
    """
    key: str
    value: JSONSerializable
    def encode(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def decode(cls, *, key, value): # -> Self:
        ...
    


class Operator(str, enum.Enum):
    lt = ...
    gt = ...
    le = ...
    ge = ...


@register(name="comparison")
@dataclass
class Comparison(NoBool):
    """
    Query binary comparison between given key's value to the specified value.

    See `Key` in this module for a more intuitive interface for comparisons.

    Parameters
    ----------
    operator : {"gt", "lt", "ge", "le"}
    key : str
        e.g. "temperature"
    value : JSONSerializable
        May be a string, number, list, or dict.

    Examples
    --------

    Search for temperature > 300.

    >>> c.search(Comparison("gt", "temperature", 300))
    """
    operator: Operator
    key: str
    value: JSONSerializable
    def __init__(self, operator, key, value) -> None:
        ...
    
    def encode(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def decode(cls, *, operator, key, value): # -> Self:
        ...
    


@register(name="contains")
@dataclass
class Contains(NoBool):
    """
    Query where a given key's value contains the specified value.

    Parameters
    ----------
    key : str
        e.g. "motors"
    value : JSONSerializable
        May be a string, number, list, or dict.

    Examples
    --------

    Search for matches where "ccd" is including the list of detectors.

    >>> c.search(Contains("detectors", "ccd"))
    """
    key: str
    value: JSONSerializable
    def encode(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def decode(cls, *, key, value): # -> Self:
        ...
    


@register(name="in")
@dataclass
class In:
    """
    Query if a given key's value is present in the specified sequence of values.

    Parameters
    ----------
    key : str
        e.g. "color", "sample.name"
    value : List[JSONSerializable]
        e.g. ["red", "blue"]

    Examples
    --------

    Search for color in ["red", "blue"]

    >>> c.search(In("color", ["red", "blue"]))
    """
    key: str
    value: List[JSONSerializable]
    def __post_init__(self): # -> None:
        ...
    
    def encode(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def decode(cls, *, key, value): # -> Self:
        ...
    


@register(name="notin")
@dataclass
class NotIn:
    """
    Query if a given key's value is not present in the specified sequence of values.

    Parameters
    ----------
    key : str
        e.g. "color", "sample.name"
    value : List[JSONSerializable]
        e.g. ["red", "blue"]

    Examples
    --------

    Search for color not in ["red", "blue"]

    >>> c.search(NotIn("color", ["red", "blue"]))
    """
    key: str
    value: List[JSONSerializable]
    def __post_init__(self): # -> None:
        ...
    
    def encode(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def decode(cls, *, key, value): # -> Self:
        ...
    


@register(name="keypresent")
@dataclass
class KeyPresent:
    """
    Query to retrieve containers that have a specific key at any level.

    Parameters
    ----------
    key : str
        e.g. "color", "sample.name"
    exists : bool
        Set to True by default, but can be set to False to find the inverse
    Examples
    --------

    Search for containers that have the key "color"

    >>> c.search(KeyPresent("color"))

    Search for containers that do not have the key "sample.name"

    >>> c.search(KeyPresent("sample.name", exists=False))
    """
    key: str
    exists: bool = ...
    def encode(self): # -> dict[str, str | bool]:
        ...
    
    @classmethod
    def decode(cls, *, key, exists): # -> Self:
        ...
    


@register(name="like")
@dataclass
class Like(NoBool):
    """
    Query for an approximate string match.

    This uses the SQL 'LIKE' operator.

    Parameters
    ----------
    key : str
        e.g. "color", "sample.name"
    pattern : str
        e.g. "Ni%"

    Examples
    --------

    Search for sample starting with "Ni"

    >>> c.search(Like("sample", "Ni%"))

    Search for detector ending with "image"

    >>> c.search(Like("detector", "%image"))

    """
    key: str
    pattern: str
    def encode(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def decode(cls, *, key, pattern): # -> Self:
        ...
    


@register(name="specs")
@dataclass(init=False)
class SpecsQuery:
    """
    Query if specs list matches all elements in include list and does not match any element in exclude list

    Parameters
    ----------
    include : List[str]
    exclude : List[str]

    Examples
    --------

    Search for specs ["foo", "bar"] and NOT "baz"

    >>> c.search(SpecsQuery(include=["foo", "bar"], exclude=["baz"]))
    """
    include: List[str]
    exclude: List[str]
    def __init__(self, include, exclude=...) -> None:
        ...
    
    def encode(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def decode(cls, *, include, exclude): # -> Self:
        ...
    


def SpecQuery(spec): # -> SpecsQuery:
    """
    Convenience function for querying if specs list contains a given spec

    Equivalent to SpecsQuery([spec]).

    Parameters
    ----------
    spec: str

    Examples
    --------

    Search for spec "foo"

    >>> c.search(Spec("foo"))
    """
    ...

@register(name="access_blob_filter")
@dataclass
class AccessBlobFilter:
    """
    Perform a query against the access_blob with two conditions.
    1. Query for a user id (i.e. username) match against the "user" field
    2. Query for if any tag in a list of tags is present in the "tags" field
    The values for these conditions are independent.

    Parameters
    ----------
    user_id : str
        e.g. "bill", "amanda"
    tags : List[JSONSerializable]
        e.g. ["tag_for_bill", "amanda_only"]


    Examples
    --------

    Search for user "bill", as well as tags in ["tag_for_bill", "useful_data"]

    >>> c.search(AccessBlobFilter("bill", ["tag_for_bill", "useful_data"]))
    """
    user_id: Optional[str]
    tags: List[str]
    def encode(self): # -> dict[str, str | List[str] | None]:
        ...
    
    @classmethod
    def decode(cls, *, user_id, tags): # -> Self:
        ...
    


@register(name="structure_family")
@dataclass(init=False)
class StructureFamilyQuery:
    """
    Query if structure_families match value

    Parameters
    ----------
    value : StructureFamily

    Examples
    --------

    Search for dataframes

    >>> c.search(StructureFamilies("dataframe"))
    """
    def __init__(self, value) -> None:
        ...
    
    value: StructureFamilyEnum
    def encode(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def decode(cls, *, value): # -> Self:
        ...
    


class Key:
    """
    Compare a key in the metadata to a value using standard Python operators.

    This itself is not a query, but *comparing* it with a value, as shown
    in the examples below, produces a query.

    Parameters
    ----------
    key : str

    Examples
    --------

    Search for equality, comparison, or membership in a collection.

    >>> c.search(Key("color") == "red")
    >>> c.search(Key("temperature") >= 300)
    >>> c.search(Key("temperature") <= 300)
    >>> c.search(Key("position") > 5.0)
    >>> c.search(Key("position") < 5.0)
    """
    def __init__(self, key) -> None:
        ...
    
    def __eq__(self, value) -> bool:
        ...
    
    def __ne__(self, value) -> bool:
        ...
    
    def __lt__(self, value) -> bool:
        ...
    
    def __gt__(self, value) -> bool:
        ...
    
    def __le__(self, value) -> bool:
        ...
    
    def __ge__(self, value) -> bool:
        ...
    


class QueryValueError(ValueError):
    ...
