"""
This type stub file was generated by pyright.
"""

import dataclasses
import functools
import adbc_driver_manager.dbapi
from abc import abstractmethod
from pathlib import Path
from typing import Dict, Literal, Optional, TYPE_CHECKING, Union
from obstore.store import AzureStore, GCSStore, LocalStore, S3Store

if TYPE_CHECKING:
    ...
__all__ = ["EmbeddedSQLStorage", "RemoteSQLStorage", "FileStorage", "SQLStorage", "ObjectStorage", "Storage", "get_storage", "parse_storage"]
SUPPORTED_OBJECT_URI_SCHEMES = ...
@dataclasses.dataclass(frozen=True)
class Storage:
    "Base class for representing storage location"
    uri: str
    def __post_init__(self): # -> None:
        ...
    


@dataclasses.dataclass(frozen=True)
class FileStorage(Storage):
    "Filesystem storage location"
    @functools.cached_property
    def path(self): # -> Path:
        ...
    
    def get_obstore_location(self, uri=...) -> LocalStore:
        """Get an obstore.store.LocalStore instance rooted at specified URI.

        Parameters
        ----------
            uri: str, optional
        """
        ...
    


@dataclasses.dataclass(frozen=True)
class ObjectStorage(Storage):
    """Bucket storage location for BLOBS

    The uri should include the bucket, but not the prefix within the bucket. This
    allows multiple ObjectStorage to point to different buckets with different
    credentials.

    Parameters
    ----------
        uri: str
            Base URI, including bucket, but without prefix
        provider: Literal["s3", "azure", "google"]
        bucket: Optional[str]
            Only required for s3 and google
        username: Optional[str]
        password: Optional[str]
        config: dict
            Additional configuration options passed to obstore store classes.
    """
    uri: str
    provider: Literal["s3", "azure", "google"]
    bucket: Optional[str] = ...
    username: Optional[str] = ...
    password: Optional[str] = ...
    config: dict = ...
    def __post_init__(self): # -> None:
        ...
    
    @classmethod
    def parse_blob_uri(cls, uri: str) -> tuple[str, str]:
        """Split a blob URI into base URI, bucket name (optionally), and the prefix.

        For example, given 'http://example.com/bucket_name/path/to/blob',
        return ('http://example.com', 'bucket_name', 'path/to/blob').
        """
        ...
    
    def get_obstore_location(self, uri=...) -> Union[S3Store, AzureStore, GCSStore]:
        """Get an obstore.store instance rooted at specified URI.

        Parameters
        ----------
            uri: str, optional
                The URI to use as the root for the obstore location. If not specified, use the base URI of
                this ObjectStorage.

        Returns
        -------
            An instance of obstore.store.S3Store, obstore.store.AzureStore, or obstore.store.GCSStore,
            depending on the provider.
        """
        ...
    


@dataclasses.dataclass(frozen=True)
class SQLStorage(Storage):
    "General purpose SQL database storage with connection pooling"
    pool_size: int = ...
    max_overflow: int = ...
    def __post_init__(self): # -> None:
        ...
    
    @abstractmethod
    def create_adbc_connection(self) -> adbc_driver_manager.dbapi.Connection:
        "Create a connection to the database."
        ...
    
    @property
    def dialect(self) -> str:
        "The database dialect (e.g. 'postgresql', 'sqlite', or 'duckdb')."
        ...
    
    def connect(self) -> adbc_driver_manager.dbapi.Connection:
        "Get a connection from the pool."
        ...
    
    def dispose(self) -> None:
        "Close all connections and dispose of the connection pool."
        ...
    


@dataclasses.dataclass(frozen=True)
class EmbeddedSQLStorage(SQLStorage):
    "File-based SQL database storage location"
    def create_adbc_connection(self) -> adbc_driver_manager.dbapi.Connection:
        ...
    


@dataclasses.dataclass(frozen=True)
class RemoteSQLStorage(SQLStorage):
    "Authenticated server-based SQL database storage location"
    username: Optional[str] = ...
    password: Optional[str] = ...
    def __post_init__(self): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @functools.cached_property
    def authenticated_uri(self): # -> str:
        ...
    
    def create_adbc_connection(self) -> adbc_driver_manager.dbapi.Connection:
        ...
    


def parse_storage(item: Union[Path, str, dict], *, pool_size: int = ..., max_overflow: int = ...) -> Storage:
    "Create a Storage object from a URI or Path."
    ...

_STORAGE: Dict[str, Storage] = ...
def register_storage(storage: Storage) -> None:
    "Stash Storage for later lookup by URI."
    ...

def get_storage(uri: str) -> Storage:
    "Look up Storage by URI."
    ...
