"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import Generic, Literal, Optional, TypeVar, Union
from pydantic import BaseModel
from .structures.array import ArrayStructure, BuiltinDtype, StructDtype
from .structures.core import Spec, StructureFamily
from .structures.data_source import Management

class Asset(BaseModel):
    id: Optional[int]
    data_uri: str
    is_directory: bool
    parameter: str
    num: int
    ...


StructureT = TypeVar("StructureT")
class DataSource(BaseModel, Generic[StructureT]):
    id: Optional[int]
    structure_family: StructureFamily
    structure: StructureT
    mimetype: str
    parameters: dict
    properties: dict
    assets: list[Asset]
    management: Management
    ...


class Schema(BaseModel):
    version: int
    def content(self): # -> dict[str, Any]:
        ...
    


class ArraySchema(Schema):
    type: Literal["array-schema"]
    data_type: Union[BuiltinDtype, StructDtype]
    ...


class ContainerSchema(Schema):
    type: Literal["container-schema"]
    ...


class TableSchema(Schema):
    type: Literal["table-schema"]
    arrow_schema: str
    ...


class Update(BaseModel):
    sequence: int = ...
    timestamp: datetime


class ChildCreated(Update):
    type: Literal["container-child-created"] = ...
    key: str
    structure_family: StructureFamily
    specs: list[Spec]
    metadata: dict
    data_sources: list[DataSource]
    access_blob: dict


class ChildMetadataUpdated(Update):
    type: Literal["container-child-metadata-updated"] = ...
    key: str
    specs: list[Spec]
    metadata: dict


class ArrayData(Update):
    type: Literal["array-data"] = ...
    mimetype: str
    shape: tuple[int, ...]
    offset: Optional[tuple[int, ...]]
    block: Optional[tuple[int, ...]]
    payload: bytes
    data_type: Union[BuiltinDtype, StructDtype]


class ArrayPatch(BaseModel):
    offset: tuple[int, ...]
    shape: tuple[int, ...]
    ...


class ArrayRef(Update):
    type: Literal["array-ref"] = ...
    data_source: DataSource[ArrayStructure]
    patch: Optional[ArrayPatch]
    uri: Optional[str]
    shape: tuple[int, ...]
    data_type: Union[BuiltinDtype, StructDtype]


class TableData(Update):
    type: Literal["table-data"] = ...
    mimetype: str
    partition: Optional[int]
    append: bool
    payload: bytes
    arrow_schema: str
