"""
This type stub file was generated by pyright.
"""

import collections.abc
import contextlib
import warnings
import yaml
from pathlib import Path
from typing import Any, Callable, Generic, Iterator, Optional, Tuple, TypeVar, Union

patch_mimetypes = ...
T = TypeVar("T")
K = TypeVar("K")
V = TypeVar("V")
class ListView(collections.abc.Sequence[V], Generic[V]):
    "An immutable view of a list."
    def __init__(self, seq: collections.abc.Sequence[V]) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __getitem__(self, index: int) -> V:
        ...
    
    def __iter__(self) -> collections.abc.Iterator[V]:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __setitem__(self, index: int, value: V):
        ...
    
    def __delitem__(self, index: int):
        ...
    
    def __add__(self, other: collections.abc.Sequence[K]) -> ListView[V | K]:
        ...
    
    def __eq__(self, other: Any) -> bool:
        ...
    


class DictView(collections.abc.Mapping[K, V], Generic[K, V]):
    "An immutable view of a dict."
    def __init__(self, d: collections.abc.Mapping[K, V]) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __getitem__(self, key: K) -> V:
        ...
    
    def __iter__(self) -> collections.abc.Iterator[K]:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __setitem__(self, key: K, value: V):
        ...
    
    def __delitem__(self, key: K):
        ...
    
    def __eq__(self, other: Any) -> bool:
        ...
    


_OneShotCachedMapWrapper = ...
class OneShotCachedMap(collections.abc.Mapping[K, V], Generic[K, V]):
    __slots__ = ...
    def __init__(self, *args, **kwargs: Callable[[], V]) -> None:
        ...
    
    def __getitem__(self, key: K) -> V:
        ...
    
    def set(self, key: K, value_factory: Callable[[], V]): # -> None:
        """
        Set key to a callable the returns value.
        """
        ...
    
    def discard(self, key: K): # -> None:
        """
        Discard a key if it is present. This is idempotent.
        """
        ...
    
    def remove(self, key: K): # -> None:
        """
        Remove a key. Raises KeyError if key not present.
        """
        ...
    
    def __len__(self) -> int:
        ...
    
    def __iter__(self) -> collections.abc.Iterator[K]:
        ...
    
    def __contains__(self, k: K) -> bool:
        ...
    
    def __getstate__(self) -> collections.abc.Mapping[K, Union[Callable[[], V], V]]:
        ...
    
    def __setstate__(self, mapping: collections.abc.Mapping[K, Union[Callable[[], V], V]]): # -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


class CachingMap(collections.abc.Mapping[K, V], Generic[K, V]):
    """
    Mapping that computes values on read and caches them in a configured cache.

    Parameters
    ----------
    mapping : dict-like
        Must map keys to callables that return values.
    cache : dict-like
        Will be used to cache values. May be ordinary dict, LRUCache, etc.
    """
    __slots__ = ...
    def __init__(self, mapping: collections.abc.Mapping[K, Callable[[], V]], cache: dict[K, V]) -> None:
        ...
    
    def __getitem__(self, key: K) -> V:
        ...
    
    def set(self, key: K, value_factory: Callable[[], V]): # -> None:
        """
        Set key to a callable the returns value.
        """
        ...
    
    def discard(self, key: K): # -> None:
        """
        Discard a key if it is present. This is idempotent.
        """
        ...
    
    def remove(self, key: K): # -> None:
        """
        Remove a key. Raises KeyError if key not present.
        """
        ...
    
    def evict(self, key: K): # -> None:
        """
        Evict a key from the internal cache. This is idempotent.

        This does *not* remove the key from the mapping.
        If it is accessed, it will be recomputed and added back to the cache.
        """
        ...
    
    def __len__(self) -> int:
        ...
    
    def __iter__(self) -> collections.abc.Iterator[K]:
        ...
    
    def __contains__(self, key: K) -> bool:
        ...
    
    def __getstate__(self) -> Tuple[collections.abc.Mapping[K, Callable[[], V]], dict[K, V]]:
        ...
    
    def __setstate__(self, state: Tuple[collections.abc.Mapping[K, Callable[[], V]], dict[K, V]]): # -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


def walk(tree, nodes=...): # -> Generator[Any, Any, None]:
    "Walk the entries in a (nested) Tree depth first."
    ...

def gen_tree(tree, nodes=..., last=...): # -> Generator[Any, Any, None]:
    "A generator of lines for the tree utility"
    ...

def tree(tree, max_lines=...): # -> None:
    """
    Print a visual sketch of Tree structure akin to UNIX `tree`.

    Parameters
    ----------
    tree : Tree
    max_lines: int or None, optional
        By default, output is truncated at 20 lines. ``None`` means "Do not
        truncate."

    Examples
    --------

    >>> tree(tree)
    ├── A
    │   ├── dog
    │   ├── cat
    │   └── monkey
    └── B
        ├── snake
        ├── bear
        └── wolf

    """
    ...

class Sentinel:
    def __init__(self, name: str) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __copy__(self) -> Sentinel:
        ...
    
    def __deepcopy__(self, memo: Sentinel) -> Sentinel:
        ...
    


UNCHANGED = ...
UNSET = ...
SingleUserPrincipal = ...
def import_object(colon_separated_string, accept_live_object=...): # -> Any:
    ...

def modules_available(*module_names): # -> bool:
    ...

def parse(file: Path) -> dict[Any, Any]:
    """
    Given a config file, parse it.

    This wraps YAML parsing and environment variable expansion.
    """
    ...

def expand_environment_variables(config: T) -> T:
    """Expand environment variables in a nested config dictionary

    VENDORED FROM dask.config.

    This function will recursively search through any nested dictionaries
    and/or lists.

    Parameters
    ----------
    config : dict, iterable, or str
        Input object to search for environment variables

    Returns
    -------
    config : same type as input

    Examples
    --------
    >>> expand_environment_variables({'x': [1, 2, '$USER']})  # doctest: +SKIP
    {'x': [1, 2, 'my-username']}
    """
    ...

@contextlib.contextmanager
def prepend_to_sys_path(*paths: Union[str, Path]) -> Iterator[None]:
    "Temporarily prepend items to sys.path."
    ...

def safe_json_dump(content, *, auto_json_types=...): # -> bytes:
    """
    Baes64-encode raw bytes, and provide a fallback if orjson numpy handling fails.

    auto_json_types: list of types, optional
        Additional types with a `to_json()` method to try to serialize automatically.
    """
    ...

class MissingDependency(ModuleNotFoundError):
    ...


class UnrecognizedExtension(ValueError):
    ...


class SerializationError(Exception):
    ...


class UnsupportedShape(SerializationError):
    ...


class UnsupportedQueryType(TypeError):
    ...


class Conflicts(Exception):
    "Prompts the server to send 409 Conflicts with message"
    ...


class BrokenLink(Exception):
    "Prompts the server to send 410 Gone with message"
    ...


APACHE_ARROW_FILE_MIME_TYPE = ...
XLSX_MIME_TYPE = ...
def get_share_tiled_path(): # -> str:
    """
    Walk up until we find share/tiled.

    Because it is outside the package, its location relative to us is up to the
    package manager. Rather than assuming that it is a specific number of
    directory levels above us, we walk upward until we find it. A file with
    long unique name helps us confirm that we have found the right directory.

    It's not clear whether being this flexible about the location of
    shared/tiled is really necessary, but JupyterHub uses a similar approach,
    so it seems possible that there is variation in the wild and that this is
    the right way to cope with that.
    """
    ...

SHARE_TILED_PATH = ...
def node_repr(tree, sample) -> str:
    ...

def bytesize_repr(num): # -> str | None:
    ...

TIME_STRING_PATTERN = ...
TIME_STRING_UNITS = ...
def parse_time_string(s): # -> int:
    """
    Accept strings like '1y', '1d', '24h'; return int seconds.

    Accepted Units:
    'y' = year
    'd' = day
    'h' = hour
    'm' = minutes
    's' = seconds
    """
    ...

def is_coroutine_callable(call: Callable[..., Any]) -> bool:
    ...

async def ensure_awaitable(func, *args, **kwargs):
    ...

def path_from_uri(uri) -> Path:
    """
    Give a URI, return a Path.

    If the URI has a scheme other than 'file', raise ValueError.

    >>> path_from_uri('file://localhost/a/b/c')  # POSIX-style
    '/a/b/c'
    >>> path_from_uri('file://localhost/C:/a/b/c')  # Windows-style
    'C:/a/b/c'
    """
    ...

SCHEME_PATTERN = ...
def ensure_uri(uri_or_path) -> str:
    "Accept a URI or file path (Windows- or POSIX-style) and return a URI."
    ...

def sanitize_uri(uri: str) -> tuple[str, Optional[str], Optional[str]]:
    "Remove the username and password from uri if they are present."
    ...

SCHEME_TO_SCHEME_PLUS_DRIVER = ...
def ensure_specified_sql_driver(uri: str) -> str:
    """
    Given a URI without a driver in the scheme, add Tiled's preferred driver.

    If a driver is already specified, the specified one will be used; it
    will NOT be overridden by this function.

    'postgresql://...' -> 'postgresql+asynpg://...'
    'sqlite://...' -> 'sqlite+aiosqlite://...'
    'postgresql+asyncpg://...' -> 'postgresql+asynpg://...'
    'postgresql+my_custom_driver://...' -> 'postgresql+my_custom_driver://...'
    '/path/to/file.db' -> 'sqlite+aiosqlite:////path/to/file.db'
    """
    ...

class catch_warning_msg(warnings.catch_warnings):
    """Backward compatible version of catch_warnings for python <3.11.

    Allows regex matching of warning message, as in filterwarnings().
    Note that this context manager is not thread-safe.
    https://docs.python.org/3.12/library/warnings.html#warnings.catch_warnings
    """
    def __init__(self, *, action=..., message=..., category=..., module=..., lineno=..., append=..., record=...) -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    


def parse_mimetype(mimetype: str) -> tuple[str, dict]:
    """
    Parse 'text/csv;header=absent' -> ('text/csv', {'header': 'absent'})
    """
    ...

class InterningLoader(yaml.loader.BaseLoader):
    ...


def interning_constructor(loader, node): # -> str:
    ...

_MESSAGE = ...
class IndexersMixin:
    """
    Provides sliceable attributes keys_indexer, items_indexer, values_indexer.

    This is just for back-ward compatibility.
    """
    keys: Any
    values: Any
    items: Any
    fn: Any
    @property
    def keys_indexer(self) -> Any:
        ...
    
    @property
    def values_indexer(self) -> Any:
        ...
    
    @property
    def items_indexer(self) -> Any:
        ...
    
