"""
This type stub file was generated by pyright.
"""

from typing import Callable
from .structures.core import Spec

class ValidationRegistry:
    """
    Register validation functions for specs
    """
    def __init__(self) -> None:
        ...
    
    def register(self, spec: Spec, func: Callable): # -> None:
        ...
    
    def dispatch(self, spec: Spec):
        ...
    
    def __call__(self, spec: Spec):
        ...
    
    def __contains__(self, spec: Spec): # -> bool:
        ...
    


class ValidationError(Exception):
    ...


async def validate_composite(spec, metadata, entry, structure_family, structure): # -> None:
    """Spec validator for Composite containers

    Imposes rules on the contents of the entry (parent container):

    1. The spec can be assigned only to containers.
    2. No nested containers are allowed.
    3. The column names of all table structures must be unique and not
       conflict with the names of any other contents.
    """
    ...

default_validation_registry = ...
