"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import Optional
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession
from .orm import APIKey, PendingSession, Principal, Session

ALL_REVISIONS = ...
REQUIRED_REVISION = ...
async def create_default_roles(db): # -> None:
    ...

async def initialize_database(engine: AsyncEngine) -> None:
    ...

async def purge_expired(db: AsyncSession, cls) -> int:
    """
    Remove expired entries.
    """
    ...

async def create_user(db: AsyncSession, identity_provider: str, id: str) -> Principal:
    ...

async def create_service(db: AsyncSession, role: str) -> Principal:
    ...

async def lookup_valid_session(db: AsyncSession, session_id: str) -> Optional[Session]:
    ...

async def lookup_valid_pending_session_by_device_code(db: AsyncSession, device_code: str) -> Optional[PendingSession]:
    ...

async def lookup_valid_pending_session_by_user_code(db: AsyncSession, user_code: str) -> Optional[PendingSession]:
    ...

async def make_admin_by_identity(db: AsyncSession, identity_provider: str, id: str) -> Principal:
    ...

async def lookup_valid_api_key(db: AsyncSession, secret: bytes) -> Optional[APIKey]:
    """
    Look up an API key. Ensure that it is valid.
    """
    ...

async def latest_principal_activity(db: AsyncSession, principal: Principal) -> Optional[datetime]:
    """
    The most recent time this Principal has logged in with an Identity,
    refreshed a Session, or used an APIKey.

    Note that activity that is authenticated using an access token is not
    captured here. As usual with JWTs, those requests do not interact with
    this database, for performance reasons. Therefore, this may lag actual
    activity by as much as the max age of an access token (default: 15
    minutes).
    """
    ...
