"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Tuple
from numpy.typing import NDArray
from tiled.adapters.core import Adapter
from ..ndslice import NDSlice
from ..structures.array import ArrayStructure
from ..structures.core import Spec
from ..type_aliases import JSON

class ArrayAdapter(Adapter[ArrayStructure]):
    """
    Wrap an array-like object in an interface that Tiled can serve.

    Examples
    --------

    Wrap any array-like.

    >>> ArrayAdapter.from_array(numpy.random.random((100, 100)))

    >>> ArrayAdapter.from_array(dask.array.from_array(numpy.random.random((100, 100)), chunks=(100, 50)))

    """
    structure_family = ...
    def __init__(self, array: NDArray[Any], structure: ArrayStructure, *, metadata: Optional[JSON] = ..., specs: Optional[List[Spec]] = ...) -> None:
        ...
    
    @classmethod
    def from_array(cls, array: NDArray[Any], *, shape: Optional[Tuple[int, ...]] = ..., chunks: Optional[Tuple[Tuple[int, ...], ...]] = ..., dims: Optional[Tuple[str, ...]] = ..., metadata: Optional[JSON] = ..., specs: Optional[List[Spec]] = ...) -> ArrayAdapter:
        ...
    
    def __repr__(self) -> str:
        ...
    
    @property
    def dims(self) -> Optional[Tuple[str, ...]]:
        ...
    
    def read(self, slice: NDSlice = ...) -> NDArray[Any]:
        ...
    
    def read_block(self, block: Tuple[int, ...], slice: NDSlice = ...) -> NDArray[Any]:
        ...
    


def slice_and_shape_from_block_and_chunks(block: Tuple[int, ...], chunks: Tuple[Tuple[int, ...], ...]) -> tuple[NDSlice, NDSlice]:
    """
    Given dask-like chunks and block id, return slice and shape of the block.
    """
    ...
