"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from pathlib import Path
from typing import Any, Iterator

class DirectoryContainer(Mapping[str, bytes]):
    """ """
    def __init__(self, directory: Path, form: Any) -> None:
        """

        Parameters
        ----------
        directory :
        form :
        """
        ...
    
    def __getitem__(self, form_key: str) -> bytes:
        """

        Parameters
        ----------
        form_key :

        Returns
        -------

        """
        ...
    
    def __setitem__(self, form_key: str, value: bytes) -> None:
        """

        Parameters
        ----------
        form_key :
        value :

        Returns
        -------

        """
        ...
    
    def __delitem__(self, form_key: str) -> None:
        """

        Parameters
        ----------
        form_key :

        Returns
        -------

        """
        ...
    
    def __iter__(self) -> Iterator[str]:
        """

        Returns
        -------

        """
        ...
    
    def __len__(self) -> int:
        """

        Returns
        -------

        """
        ...
    
