"""
This type stub file was generated by pyright.
"""

from abc import ABC
from collections.abc import Set
from typing import Any, Generic, List, Optional, TypeVar
from tiled.storage import Storage
from tiled.structures.core import Spec, StructureFamily
from tiled.structures.root import Structure
from tiled.type_aliases import JSON

S = TypeVar("S", bound=Structure)
class Adapter(ABC, Generic[S]):
    structure_family: StructureFamily
    def __init__(self, structure: S, *, metadata: Optional[JSON] = ..., specs: Optional[List[Spec]] = ...) -> None:
        ...
    
    def metadata(self) -> JSON:
        ...
    
    @property
    def specs(self) -> List[Spec]:
        ...
    
    @specs.setter
    def specs(self, value: List[Spec]) -> None:
        ...
    
    def structure(self) -> S:
        ...
    
    @classmethod
    def supported_storage(cls) -> Set[type[Storage]]:
        ...
    


A = TypeVar("A", bound=Adapter[Any])
