"""
This type stub file was generated by pyright.
"""

from datetime import datetime, timedelta
from typing import Any, Dict, Generic, Iterator, List, Optional, TYPE_CHECKING, Tuple, Union
from tiled.adapters.container import ContainerAdapter
from tiled.adapters.core import A
from collections.abc import Mapping
from ..iterviews import ItemsView, KeysView, ValuesView
from ..server.schemas import SortingItem
from ..structures.core import Spec, StructureFamily
from ..type_aliases import JSON
from ..utils import Sentinel
from .utils import IndexersMixin

if TYPE_CHECKING:
    ...
class MapAdapter(Generic[A], ContainerAdapter[A], IndexersMixin):
    """
    Adapt any mapping (dictionary-like object) to Tiled.
    """
    query_registry = ...
    register_query = ...
    register_query_lazy = ...
    def __init__(self, mapping: Mapping[str, A], *, metadata: Optional[JSON] = ..., sorting: Optional[List[SortingItem]] = ..., specs: Optional[List[Spec]] = ..., entries_stale_after: Optional[timedelta] = ..., metadata_stale_after: Optional[timedelta] = ..., must_revalidate: bool = ...) -> None:
        """
        Create a simple Adapter from any mapping (e.g. dict, OneShotCachedMap).

        Parameters
        ----------
        mapping : dict-like
        metadata : dict, optional
        specs : List[str], optional
        sorting : List[Tuple[str, int]], optional
        specs : List[str], optional
        entries_stale_after: timedelta
            This server uses this to communicate to the client how long
            it should rely on a local cache before checking back for changes.
        metadata_stale_after: timedelta
            This server uses this to communicate to the client how long
            it should rely on a local cache before checking back for changes.
        must_revalidate : bool
            Whether the client should strictly refresh stale cache items.
        """
        ...
    
    @property
    def must_revalidate(self) -> bool:
        """

        Returns
        -------

        """
        ...
    
    @must_revalidate.setter
    def must_revalidate(self, value: bool) -> None:
        """

        Parameters
        ----------
        value :

        Returns
        -------

        """
        ...
    
    @property
    def sorting(self) -> List[SortingItem]:
        """

        Returns
        -------

        """
        ...
    
    def __repr__(self) -> str:
        """

        Returns
        -------

        """
        ...
    
    def __getitem__(self, key: str) -> A:
        """

        Parameters
        ----------
        key :

        Returns
        -------

        """
        ...
    
    def __iter__(self) -> Iterator[str]:
        """

        Returns
        -------

        """
        ...
    
    def __len__(self) -> int:
        """

        Returns
        -------

        """
        ...
    
    def keys(self) -> KeysView:
        """

        Returns
        -------

        """
        ...
    
    def values(self) -> ValuesView:
        """

        Returns
        -------

        """
        ...
    
    def items(self) -> ItemsView:
        """

        Returns
        -------

        """
        ...
    
    @property
    def metadata_stale_at(self) -> Optional[datetime]:
        """

        Returns
        -------

        """
        ...
    
    @property
    def entries_stale_at(self) -> Optional[datetime]:
        """

        Returns
        -------

        """
        ...
    
    def new_variation(self, *args: Any, mapping: Union[Sentinel, Mapping[str, A]] = ..., metadata: Union[Sentinel, JSON] = ..., sorting: Union[Sentinel, List[SortingItem]] = ..., must_revalidate: Union[Sentinel, bool] = ..., **kwargs: Any) -> MapAdapter[A]:
        """

        Parameters
        ----------
        args :
        mapping :
        metadata :
        sorting :
        must_revalidate :
        kwargs :

        Returns
        -------

        """
        ...
    
    def read(self, fields: Optional[str] = ...) -> MapAdapter[A]:
        """

        Parameters
        ----------
        fields :

        Returns
        -------

        """
        ...
    
    def search(self, query: Any) -> Any:
        """

        Parameters
        ----------
        query :

        Returns
        -------
                Return a Adapter with a subset of the mapping.
        """
        ...
    
    def get_distinct(self, metadata: JSON, structure_families: StructureFamily, specs: List[Spec], counts: int) -> Dict[str, Any]:
        """

        Parameters
        ----------
        metadata :
        structure_families :
        specs :
        counts :

        Returns
        -------

        """
        ...
    
    def sort(self, sorting: SortingItem) -> MapAdapter[A]:
        """

        Parameters
        ----------
        sorting :

        Returns
        -------

        """
        ...
    


def walk_string_values(tree: MapAdapter[Any], node: Optional[Any] = ...) -> Iterator[str]:
    """
    >>> list(
    ...     walk_string_values(
    ...         {'a': {'b': {'c': 'apple', 'd': 'banana'},
    ...          'e': ['cat', 'dog']}, 'f': 'elephant'}
    ...     )
    ... )
    ['apple', 'banana', 'cat', 'dog', 'elephant']

    Parameters
    ----------
    tree :
    node :

    Returns
    -------
    """
    ...

def counter_to_dict(counter: Dict[str, Any], counts: Any) -> List[Dict[str, Any]]:
    """

    Parameters
    ----------
    counter :
    counts :

    Returns
    -------

    """
    ...

def iter_child_metadata(query_key: Any, tree: MapAdapter[A]) -> Iterator[Tuple[str, Any, Any]]:
    """

    Parameters
    ----------
    query_key :
    tree :

    Returns
    -------

    """
    ...

def full_text_search(query: Any, tree: MapAdapter[A]) -> MapAdapter[A]:
    """

    Parameters
    ----------
    query :
    tree :

    Returns
    -------

    """
    ...

def regex(query: Any, tree: MapAdapter[A]) -> MapAdapter[A]:
    """

    Parameters
    ----------
    query :
    tree :

    Returns
    -------

    """
    ...

def eq(query: Any, tree: MapAdapter[A]) -> MapAdapter[A]:
    """

    Parameters
    ----------
    query :
    tree :

    Returns
    -------

    """
    ...

def noteq(query: Any, tree: MapAdapter[A]) -> MapAdapter[A]:
    """

    Parameters
    ----------
    query :
    tree :

    Returns
    -------

    """
    ...

def contains(query: Any, tree: MapAdapter[A]) -> MapAdapter[A]:
    """

    Parameters
    ----------
    query :
    tree :

    Returns
    -------

    """
    ...

def comparison(query: Any, tree: MapAdapter[A]) -> MapAdapter[A]:
    """

    Parameters
    ----------
    query :
    tree :

    Returns
    -------

    """
    ...

def notin(query: Any, tree: MapAdapter[A]) -> MapAdapter[A]:
    """

    Parameters
    ----------
    query :
    tree :

    Returns
    -------

    """
    ...

def key_present(query: Any, tree: MapAdapter[A]) -> MapAdapter[A]:
    """

    Parameters
    ----------
    query :
    tree :

    Returns
    -------

    """
    ...

def specs(query: Any, tree: MapAdapter[A]) -> MapAdapter[A]:
    """

    Parameters
    ----------
    query :
    tree :

    Returns
    -------

    """
    ...

def structure_family(query: Any, tree: MapAdapter[A]) -> MapAdapter[A]:
    """

    Parameters
    ----------
    query :
    tree :

    Returns
    -------

    """
    ...

def keys_filter(query: Any, tree: MapAdapter[A]) -> MapAdapter[A]:
    """

    Parameters
    ----------
    query :
    tree :

    Returns
    -------

    """
    ...

class _HIGH_SORTER_CLASS:
    """
    Enables sort to work when metadata is sparse
    """
    def __lt__(self, other: _HIGH_SORTER_CLASS) -> bool:
        """

        Parameters
        ----------
        other :

        Returns
        -------

        """
        ...
    
    def __gt__(self, other: _HIGH_SORTER_CLASS) -> bool:
        """

        Parameters
        ----------
        other :

        Returns
        -------

        """
        ...
    


_HIGH_SORTER = ...
