"""
This type stub file was generated by pyright.
"""

import dask.dataframe
import pandas
import sparse
from abc import abstractmethod
from collections.abc import Mapping
from typing import Any, Dict, List, Literal, Optional, Protocol, Set, Tuple, Union
from numpy.typing import NDArray
from ..ndslice import NDSlice
from ..storage import Storage
from ..structures.array import ArrayStructure
from ..structures.awkward import AwkwardStructure
from ..structures.core import Spec, StructureFamily
from ..structures.sparse import SparseStructure
from ..structures.table import TableStructure
from ..type_aliases import JSON
from .awkward_directory_container import DirectoryContainer

class BaseAdapter(Protocol):
    supported_storage: Set[type[Storage]]
    @abstractmethod
    def metadata(self) -> JSON:
        ...
    
    @abstractmethod
    def specs(self) -> List[Spec]:
        ...
    


class ContainerAdapter(Mapping[str, "AnyAdapter"], BaseAdapter):
    structure_family: Literal[StructureFamily.container]
    @abstractmethod
    def structure(self) -> None:
        ...
    


class ArrayAdapter(BaseAdapter, Protocol):
    structure_family: Literal[StructureFamily.array]
    @abstractmethod
    def structure(self) -> ArrayStructure:
        ...
    
    @abstractmethod
    def read(self, slice: NDSlice) -> NDArray[Any]:
        ...
    
    @abstractmethod
    def read_block(self, block: Tuple[int, ...]) -> NDArray[Any]:
        ...
    


class AwkwardAdapter(BaseAdapter, Protocol):
    structure_family: Literal[StructureFamily.awkward]
    @abstractmethod
    def structure(self) -> AwkwardStructure:
        ...
    
    @abstractmethod
    def read(self) -> NDArray[Any]:
        ...
    
    @abstractmethod
    def read_buffers(self, form_keys: Optional[List[str]] = ...) -> Dict[str, Any]:
        ...
    
    @abstractmethod
    def write(self, container: DirectoryContainer) -> None:
        ...
    


class SparseAdapter(BaseAdapter, Protocol):
    structure_family: Literal[StructureFamily.sparse] = ...
    @abstractmethod
    def structure(self) -> SparseStructure:
        ...
    
    def read(self, slice: NDSlice) -> sparse.COO:
        ...
    
    def read_block(self, block: Tuple[int, ...]) -> sparse.COO:
        ...
    


class TableAdapter(BaseAdapter, Protocol):
    structure_family: Literal[StructureFamily.table] = ...
    @abstractmethod
    def structure(self) -> TableStructure:
        ...
    
    @abstractmethod
    def read(self, fields: List[str]) -> Union[dask.dataframe.DataFrame, pandas.DataFrame]:
        ...
    
    @abstractmethod
    def read_partition(self, partition: int, fields: Optional[str] = ...) -> Union[dask.dataframe.DataFrame, pandas.DataFrame]:
        ...
    
    @abstractmethod
    def __getitem__(self, key: str) -> ArrayAdapter:
        ...
    


AnyAdapter = Union[ArrayAdapter, AwkwardAdapter, ContainerAdapter, SparseAdapter, TableAdapter]
