"""
This type stub file was generated by pyright.
"""

import dask.array
import numpy as np
from typing import Any, Optional, Tuple, Union
from tiled.adapters.core import A, S
from ..structures.data_source import DataSource

__all__ = ["IndexersMixin", "asset_parameters_to_adapter_kwargs", "init_adapter_from_catalog"]
class IndexCallable:
    """
    DEPRECATED and no longer used internally

    Provide getitem syntax for functions

    >>> def inc(x):
    ...     return x + 1

    >>> I = IndexCallable(inc)
    >>> I[3]
    4

    Vendored from dask
    """
    __slots__ = ...
    def __init__(self, fn: Any) -> None:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    


def asset_parameters_to_adapter_kwargs(data_source: DataSource[Any]) -> dict[str, Any]:
    """Transform database representation of Adapter parameters to Python representation."""
    ...

def init_adapter_from_catalog(adapter_cls: type[A], data_source: DataSource[S], node: Any, /, **kwargs: Optional[Any]) -> A:
    """Factory function to produce Adapter instances given their parameters encoded in data sources"""
    ...

def force_reshape(arr: Union[np.array, dask.array.Array], desired_shape: Tuple[int, ...]) -> Union[np.array, dask.array.Array]:
    """Reshape a numpy or dask array to match the desired shape, if possible.

    Parameters
    ----------

    arr : Union[np.array, dask.array.Array]
        The original ND array to be reshaped
    desired_shape : Tuple[int, ...]
        The desired shape of the resulting array

    Returns
    -------

    A view of the original array
    """
    ...
