"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Union
from fastapi import APIRouter, FastAPI
from ..access_control.protocols import AccessPolicy
from ..config import Authentication, Config
from ..media_type_registration import CompressionRegistry, SerializationRegistry
from ..query_registration import QueryRegistry
from ..type_aliases import AppTask
from ..validation_registration import ValidationRegistry

SAFE_METHODS = ...
SENSITIVE_COOKIES = ...
CSRF_HEADER_NAME = ...
CSRF_QUERY_PARAMETER = ...
MINIMUM_SUPPORTED_PYTHON_CLIENT_VERSION = ...
logger = ...
handler = ...
current_principal = ...
def custom_openapi(app): # -> dict[str, Any]:
    """
    The app's openapi method will be monkey-patched with this.

    This is the approach the documentation recommends.

    https://fastapi.tiangolo.com/advanced/extending-openapi/
    """
    ...

def build_app(tree, authentication: Optional[Authentication] = ..., server_settings=..., query_registry: Optional[QueryRegistry] = ..., serialization_registry: Optional[SerializationRegistry] = ..., deserialization_registry: Optional[SerializationRegistry] = ..., compression_registry: Optional[CompressionRegistry] = ..., validation_registry: Optional[ValidationRegistry] = ..., tasks: Optional[dict[str, list[AppTask]]] = ..., scalable=..., access_policy: Optional[AccessPolicy] = ..., include_routers: Optional[list[APIRouter]] = ...): # -> FastAPI:
    """
    Serve a Tree

    Parameters
    ----------
    tree : Tree
    authentication: dict, optional
        Dict of authentication configuration.
    server_settings: dict, optional
        Dict of other server configuration.
    access_policy: AccessPolicy, optional
        AccessPolicy object encoding rules for which users can see which entries.
    """
    ...

def build_app_from_config(config: Union[Config, dict[str, Any]], scalable=...): # -> FastAPI:
    """
    Convenience function that calls build_app(...) given config as parsed Config instance

    If passed an unparsed dict, it will attempt to convert it to Config but
    will omit any path handling around imports.
    """
    ...

def app_factory(): # -> FastAPI:
    """
    Return an ASGI app instance.

    Use a configuration file at the path specified by the environment variable
    TILED_CONFIG or, if unset, at the default path "./config.yml".

    This is intended to be used for horizontal deployment (using gunicorn, for
    example) where only a module and instance or factory can be specified.
    """
    ...

def __getattr__(name): # -> FastAPI:
    """
    This supports tiled.server.app.app by creating app on demand.
    """
    ...

def print_server_info(web_app: FastAPI, host: str = ..., port: int = ..., include_api_key: bool = ...): # -> None:
    ...

class UnscalableConfig(Exception):
    ...
