"""
This type stub file was generated by pyright.
"""

from typing import Annotated, Any, Callable, List, Optional, Sequence
from fastapi import APIRouter, Header, Request, WebSocket
from fastapi.security import SecurityScopes
from fastapi.security.api_key import APIKeyHeader
from sqlalchemy.ext.asyncio import AsyncSession
from tiled.authenticators import ProxiedOIDCAuthenticator
from pydantic import BaseModel
from ..type_aliases import AccessTags
from . import schemas
from .protocols import ExternalAuthenticator, InternalAuthenticator, UserSessionState
from .settings import Settings

ALGORITHM = ...
API_KEY_LIMIT = ...
SESSION_LIMIT = ...
DEVICE_CODE_MAX_AGE = ...
DEVICE_CODE_POLLING_INTERVAL = ...
def utcnow(): # -> datetime:
    "UTC now with second resolution"
    ...

class Token(BaseModel):
    access_token: str
    token_type: str
    ...


class TokenData(BaseModel):
    username: Optional[str] = ...


class StrictAPIKeyHeader(APIKeyHeader):
    """
    APIKeyHeader does not enforce that the scheme matches the expected, potentially
    leading to the case where Bearer tokens are treated as API keys.
    Additionally strips the scheme, as expected by current handling.
    """
    async def __call__(self, request: Request) -> Optional[str]:
        ...
    


oauth2_scheme = ...
def create_access_token(data, secret_key, expires_delta): # -> str:
    ...

def create_refresh_token(session_id, secret_key, expires_delta): # -> str:
    ...

def decode_token(token: str, secret_keys: List[str], proxied_authenticator: Optional[ProxiedOIDCAuthenticator] = ...) -> dict[str, Any]:
    ...

async def get_api_key(api_key_query: Optional[str] = ..., api_key_header: Optional[str] = ..., api_key_cookie: Optional[str] = ...) -> Optional[str]:
    ...

def headers_for_401(request: Request, security_scopes: SecurityScopes): # -> dict[str, str]:
    ...

async def get_decoded_access_token(request: Request, security_scopes: SecurityScopes, access_token: str = ..., settings: Settings = ...): # -> dict[str, Any] | None:
    ...

async def get_session_state(decoded_access_token=...): # -> Any | None:
    ...

async def get_access_tags_from_api_key(api_key: str, authenticated: bool, db: Optional[AsyncSession]) -> Optional[AccessTags]:
    ...

async def get_current_access_tags(request: Request, api_key: Optional[str] = ..., db_factory: Callable[[], Optional[AsyncSession]] = ...) -> Optional[AccessTags]:
    ...

def get_api_key_websocket(authorization: Annotated[Optional[str], Header()] = ...) -> Optional[str]:
    ...

async def get_current_access_tags_websocket(websocket: WebSocket, api_key: Optional[str] = ..., db_factory: Callable[[], Optional[AsyncSession]] = ...) -> Optional[AccessTags]:
    ...

async def move_api_key(request: Request, api_key: Optional[str] = ...): # -> None:
    """
    Move API key from query parameter to cookie.

    When a URL with an API key in the query parameter is opened in a browser,
    the API key is set as a cookie so that subsequent requests from the browser
    are authenticated. (This approach was inspired by Jupyter notebook.)
    """
    ...

async def get_scopes_from_api_key(api_key: str, settings: Settings, authenticated: bool, db: Optional[AsyncSession]) -> Sequence[str]:
    ...

async def get_current_scopes(request: Request, decoded_access_token: Optional[dict[str, Any]] = ..., api_key: Optional[str] = ..., settings: Settings = ..., db_factory: Callable[[], Optional[AsyncSession]] = ...) -> set[str]:
    ...

async def get_current_scopes_websocket(websocket: WebSocket, api_key: Optional[str] = ..., settings: Settings = ..., db_factory: Callable[[], Optional[AsyncSession]] = ...) -> set[str]:
    ...

async def check_scopes(request: Request, security_scopes: SecurityScopes, scopes: set[str] = ..., settings: Settings = ...) -> None:
    ...

async def get_current_principal_from_api_key(api_key: str, authenticated: bool, db: AsyncSession, settings: Settings): # -> Principal | None:
    ...

async def get_current_principal_websocket(websocket: WebSocket, api_key: Optional[str] = ..., settings: Settings = ..., db_factory: Callable[[], Optional[AsyncSession]] = ...): # -> Principal | None:
    ...

async def get_current_principal(request: Request, security_scopes: SecurityScopes, access_token: str = ..., decoded_access_token: str = ..., api_key: str = ..., settings: Settings = ..., db_factory: Callable[[], Optional[AsyncSession]] = ..., _=...) -> Optional[schemas.Principal]:
    """
    Get current Principal from:
    - API key in 'api_key' query parameter
    - API key in header 'Authorization: Apikey ...'
    - API key in cookie 'tiled_api_key'
    - OAuth2 JWT access token in header 'Authorization: Bearer ...'

    If anonymous access is allowed, Principal will be `None`.
    If the server is configured with a "single-user API key", then
    the Principal will also be `None` - but is differentiated for
    logging with a SingleUserPrincipal sentinel
    """
    ...

async def create_pending_session(db: AsyncSession): # -> dict[str, str]:
    ...

async def create_session(settings: Settings, db: AsyncSession, identity_provider, id, state: UserSessionState = ...): # -> Session | None:
    ...

async def create_tokens_from_session(settings: Settings, db: AsyncSession, session, provider): # -> dict[str, str | float | dict[str, Column[str] | Any] | Any]:
    ...

def add_external_routes(router: APIRouter, provider: str, authenticator: ExternalAuthenticator): # -> None:
    ...

def add_internal_routes(router: APIRouter, provider: str, authenticator: InternalAuthenticator): # -> None:
    "Register a handle_credentials route function for this Authenticator."
    ...

async def generate_apikey(db: AsyncSession, principal, apikey_params, request): # -> Response | MsgpackResponse | NumpySafeJSONResponse:
    ...

def authentication_router() -> APIRouter:
    ...
