"""
This type stub file was generated by pyright.
"""

from starlette.types import ASGIApp, Message, Receive, Scope, Send

class CompressionMiddleware:
    def __init__(self, app: ASGIApp, compression_registry, minimum_size: int = ...) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    


class CompressionResponder:
    def __init__(self, app: ASGIApp, minimum_size: int, accepted: set, compression_registry) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    
    async def send_compressed(self, message: Message) -> None:
        ...
    


async def unattached_send(message: Message) -> None:
    ...
