"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncGenerator
from typing import Callable, Optional, Union
from sqlalchemy.engine import URL
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession
from ..server.settings import DatabaseSettings, Settings

DEFAULT_ECHO = ...
_connection_pools: dict[DatabaseSettings, AsyncEngine] = ...
def open_database_connection_pool(database_settings: DatabaseSettings) -> AsyncEngine:
    ...

async def close_database_connection_pool(database_settings: DatabaseSettings): # -> None:
    ...

def get_database_engine(settings: Union[Settings, DatabaseSettings] = ...) -> AsyncEngine:
    ...

async def get_database_session_factory(engine: AsyncEngine = ...) -> AsyncGenerator[Callable[[], Optional[AsyncSession]]]:
    ...

def json_serializer(obj): # -> str:
    "The PostgreSQL JSON serializer requires str, not bytes."
    ...

def is_memory_sqlite(url: Union[URL, str]) -> bool:
    """
    Check if a SQLAlchemy URL is a memory-backed SQLite database.

    Handles various memory database URL formats:
    - sqlite:///:memory:
    - sqlite:///file::memory:?cache=shared
    - sqlite://
    - etc.
    """
    ...
