"""
This type stub file was generated by pyright.
"""

from typing import Any
from fastapi import Response
from starlette.responses import JSONResponse
from . import schemas

_FILTER_PARAM_PATTERN = ...
_LOCAL_TZINFO = ...
INLINED_CONTENTS_LIMIT = ...
DEPTH_LIMIT = ...
DEFAULT_PAGE_SIZE = ...
MAX_PAGE_SIZE = ...
async def len_or_approx(tree, exact=..., threshold=...):
    """Calculate the length of a tree, either exactly or approximately

    Prefer approximate length if implemented. (It's cheaper.)

    Parameters
    ----------
    tree : Tree
        The tree to calculate the length of.
    exact : bool, optional
        If True, always return the exact length. If False, return an
        approximate length if available.
    threshold : int
        If the exact length is less than this threshold, return it;
        otherwise, return an approximate length of this lower bound.
        If set to -1, return the exact length.
        Only used if `exact` is False.

    Returns
    -------
    int
        The length of the tree, either exact or approximate.
    """
    ...

def pagination_links(base_url, route, path_parts, offset, limit, length_hint): # -> dict[str, str | None]:
    ...

async def apply_search(tree, filters, query_registry): # -> MapAdapter[Any]:
    ...

def apply_sort(tree, sort):
    ...

async def construct_entries_response(query_registry, tree, route, path, offset, limit, fields, select_metadata, omit_links, include_data_sources, filters, sort, base_url, media_type, max_depth, exact_count_limit): # -> tuple[Response[list[Any], dict[str, str | None], dict[str, Any]], datetime | Any | None, Any | bool]:
    "Construct a response for the `/search` endpoint"
    ...

DEFAULT_MEDIA_TYPES = ...
async def construct_revisions_response(entry, base_url, route, path, offset, limit, media_type): # -> Response[list[Any], dict[str, str | None], dict[str, int]]:
    ...

async def construct_data_response(structure_family, serialization_registry, payload, metadata, request, format=..., specs=..., expires=..., filename=..., filter_for_access=...): # -> Response | StreamingResponse:
    ...

async def construct_resource(base_url, path_parts, entry, fields, select_metadata, omit_links, include_data_sources, media_type, max_depth, exact_count_limit, depth=...):
    ...

class NumpySafeJSONResponse(JSONResponse):
    def __init__(self, *args, metrics, **kwargs) -> None:
        ...
    
    def render(self, content: Any) -> bytes:
        ...
    


class MsgpackResponse(Response):
    media_type = ...
    def __init__(self, *args, metrics, **kwargs) -> None:
        ...
    
    def render(self, content: Any, _reentered=...) -> bytes:
        ...
    


JSON_MIME_TYPE = ...
MSGPACK_MIME_TYPE = ...
HTTP_EXPIRES_HEADER_FORMAT = ...
def resolve_media_type(request): # -> Literal['application/json', 'application/x-msgpack']:
    ...

def json_or_msgpack(request, content, expires=..., headers=..., status_code=...): # -> Response | MsgpackResponse | NumpySafeJSONResponse:
    ...

def get_websocket_envelope_formatter(envelope_format: schemas.EnvelopeFormat, entry, deserialization_registry): # -> Callable[..., CoroutineType[Any, Any, None]] | None:
    ...

class UnsupportedMediaTypes(Exception):
    ...


class NoEntry(KeyError):
    ...


class WrongTypeForRoute(Exception):
    ...


def asdict(dc): # -> dict[str, Any] | dict[Any, Any] | None:
    "Compat for converting dataclass or pydantic.BaseModel to dict."
    ...
