"""
This type stub file was generated by pyright.
"""

import pydantic_settings
from typing import List, Optional
from fastapi import Request
from ..access_control.protocols import AccessPolicy
from ..adapters.protocols import AnyAdapter
from ..structures.core import StructureFamily
from ..type_aliases import AccessTags, Scopes
from .schemas import Principal

def get_root_tree(request: Request): # -> Any:
    ...

async def get_entry(path: str, security_scopes: List[str], principal: Optional[Principal], authn_access_tags: Optional[AccessTags], authn_scopes: Scopes, root_tree: pydantic_settings.BaseSettings, session_state: dict, metrics: dict, structure_families: Optional[set[StructureFamily]] = ..., access_policy: Optional[AccessPolicy] = ...) -> AnyAdapter:
    """
    Obtain a node in the tree from its path.

    Walk down the path starting from the root of the tree and filter
    access by the specified scopes.

    session_state is an optional dictionary passed in the session token
    """
    ...

def block(block: str = ...): # -> tuple[()] | tuple[int, ...]:
    "Specify and parse a block index parameter."
    ...

def expected_shape(expected_shape: Optional[str] = ...): # -> tuple[()] | tuple[int, ...] | None:
    "Specify and parse an expected_shape parameter."
    ...

def shape_param(shape: str = ...): # -> tuple[int, ...]:
    "Specify and parse a shape parameter."
    ...

def offset_param(offset: str = ...): # -> tuple[int, ...]:
    "Specify and parse an offset parameter."
    ...

def patch_shape_param(patch_shape: Optional[str] = ...): # -> tuple[int, ...] | None:
    "Specify and parse an array patch shape parameter."
    ...

def patch_offset_param(patch_offset: Optional[str] = ...): # -> tuple[int, ...] | None:
    "Specify and parse an array patch offset parameter."
    ...
