"""
This type stub file was generated by pyright.
"""

import importlib.util
from dask.tokenize import normalize_token
from dask.base import normalize_token

if importlib.util.find_spec("dask.tokenize"):
    ...
else:
    ...
def tokenize(obj): # -> str:
    ...

@normalize_token.register_lazy("h5py")
def register_h5py(): # -> None:
    ...
