"""
This type stub file was generated by pyright.
"""

from typing import TypeVar, Union
from fastapi import APIRouter
from tiled.media_type_registration import SerializationRegistry
from tiled.query_registration import QueryRegistry
from tiled.server.protocols import ExternalAuthenticator, InternalAuthenticator
from ..validation_registration import ValidationRegistry

T = TypeVar("T")
def get_router(query_registry: QueryRegistry, serialization_registry: SerializationRegistry, deserialization_registry: SerializationRegistry, validation_registry: ValidationRegistry, authenticators: dict[str, Union[ExternalAuthenticator, InternalAuthenticator]]) -> APIRouter:
    ...

def get_metrics_router() -> APIRouter:
    ...
