"""
This type stub file was generated by pyright.
"""

import enum
import uuid
import tiled.authn_database.orm
import tiled.catalog.orm
from datetime import datetime
from typing import Any, Dict, Generic, List, Optional, TYPE_CHECKING, TypeVar, Union
from pydantic import Field, SecretStr, StringConstraints
from typing_extensions import Annotated
from ..structures.array import ArrayStructure
from ..structures.awkward import AwkwardStructure
from ..structures.core import Spec, StructureFamily
from ..structures.data_source import Management
from ..structures.sparse import SparseStructure
from ..structures.table import TableStructure

if TYPE_CHECKING:
    ...
DataT = TypeVar("DataT")
LinksT = TypeVar("LinksT")
MetaT = TypeVar("MetaT")
StructureT = TypeVar("StructureT")
MAX_ALLOWED_SPECS = ...
class Error(pydantic.BaseModel):
    code: int
    message: str
    ...


class Response(pydantic.BaseModel, Generic[DataT, LinksT, MetaT]):
    data: Optional[DataT]
    error: Optional[Error] = ...
    links: Optional[LinksT] = ...
    meta: Optional[MetaT] = ...
    @pydantic.field_validator("error")
    def check_consistency(cls, v, values):
        ...
    


class PaginationLinks(pydantic.BaseModel):
    self: str
    next: str
    prev: str
    first: str
    last: str
    ...


class EntryFields(str, enum.Enum):
    metadata = ...
    structure_family = ...
    structure = ...
    count = ...
    sorting = ...
    specs = ...
    data_sources = ...
    none = ...
    access_blob = ...


class NodeStructure(pydantic.BaseModel):
    contents: Optional[Dict[str, Any]]
    count: int
    model_config = ...


class SortingDirection(int, enum.Enum):
    ASCENDING = ...
    DESCENDING = ...


class SortingItem(pydantic.BaseModel):
    key: str
    direction: SortingDirection
    ...


Specs = Annotated[List[Spec], Field(max_length=MAX_ALLOWED_SPECS)]
class Asset(pydantic.BaseModel):
    data_uri: str
    is_directory: bool
    parameter: Optional[str] = ...
    num: Optional[int] = ...
    id: Optional[int] = ...
    @classmethod
    def from_orm(cls, orm: tiled.catalog.orm.Asset) -> Asset:
        ...
    
    @classmethod
    def from_assoc_orm(cls, orm): # -> Self:
        ...
    


class Revision(pydantic.BaseModel):
    revision_number: int
    metadata: dict
    specs: Specs
    access_blob: dict
    time_updated: datetime
    @classmethod
    def from_orm(cls, orm: tiled.catalog.orm.Revision) -> Revision:
        ...
    


class DataSource(pydantic.BaseModel, Generic[StructureT]):
    id: Optional[int] = ...
    structure_family: StructureFamily
    structure: Optional[StructureT]
    mimetype: Optional[str] = ...
    parameters: dict = ...
    properties: dict = ...
    assets: List[Asset] = ...
    management: Management = ...
    model_config = ...
    @classmethod
    def from_orm(cls, orm: tiled.catalog.orm.DataSource) -> DataSource:
        ...
    


class NodeAttributes(pydantic.BaseModel):
    ancestors: List[str]
    structure_family: Optional[StructureFamily] = ...
    specs: Optional[Specs] = ...
    metadata: Optional[Dict] = ...
    structure: Optional[Union[ArrayStructure, AwkwardStructure, SparseStructure, NodeStructure, TableStructure,]] = ...
    access_blob: Optional[Dict] = ...
    sorting: Optional[List[SortingItem]] = ...
    data_sources: Optional[List[DataSource]] = ...
    model_config = ...


AttributesT = TypeVar("AttributesT")
ResourceMetaT = TypeVar("ResourceMetaT")
ResourceLinksT = TypeVar("ResourceLinksT")
class SelfLinkOnly(pydantic.BaseModel):
    self: str
    ...


class ContainerLinks(pydantic.BaseModel):
    self: str
    search: str
    full: str
    ...


class ArrayLinks(pydantic.BaseModel):
    self: str
    full: str
    block: str
    ...


class AwkwardLinks(pydantic.BaseModel):
    self: str
    buffers: str
    full: str
    ...


class DataFrameLinks(pydantic.BaseModel):
    self: str
    full: str
    partition: str
    ...


class SparseLinks(pydantic.BaseModel):
    self: str
    full: str
    block: str
    ...


resource_links_type_by_structure_family = ...
class EmptyDict(pydantic.BaseModel):
    ...


class ContainerMeta(pydantic.BaseModel):
    count: int
    ...


class Resource(pydantic.BaseModel, Generic[AttributesT, ResourceLinksT, ResourceMetaT]):
    "A JSON API Resource"
    id: Union[str, uuid.UUID]
    attributes: AttributesT
    links: Optional[ResourceLinksT] = ...
    meta: Optional[ResourceMetaT] = ...


class AccessAndRefreshTokens(pydantic.BaseModel):
    access_token: str
    expires_in: int
    refresh_token: str
    refresh_token_expires_in: int
    token_type: str
    ...


class RefreshToken(pydantic.BaseModel):
    refresh_token: str
    ...


class DeviceCode(pydantic.BaseModel):
    device_code: str
    grant_type: str
    ...


class PrincipalType(str, enum.Enum):
    user = ...
    service = ...
    external = ...


class Identity(pydantic.BaseModel):
    model_config = ...
    id: Annotated[str, StringConstraints(max_length=255)]
    provider: Annotated[str, StringConstraints(max_length=255)]
    latest_login: Optional[datetime] = ...
    @classmethod
    def from_orm(cls, orm: tiled.authn_database.orm.Identity) -> Identity:
        ...
    


class Role(pydantic.BaseModel):
    model_config = ...
    name: str
    scopes: List[str]
    @classmethod
    def from_orm(cls, orm: tiled.authn_database.orm.Role) -> Role:
        ...
    


class APIKey(pydantic.BaseModel):
    model_config = ...
    first_eight: Annotated[str, StringConstraints(min_length=8, max_length=8)]
    expiration_time: Optional[datetime] = ...
    note: Optional[Annotated[str, StringConstraints(max_length=255)]] = ...
    scopes: List[str]
    access_tags: Optional[List[str]] = ...
    latest_activity: Optional[datetime] = ...
    @classmethod
    def from_orm(cls, orm: tiled.authn_database.orm.APIKey) -> APIKey:
        ...
    


class APIKeyWithSecret(APIKey):
    secret: str
    @classmethod
    def from_orm(cls, orm: tiled.authn_database.orm.APIKeyWithSecret, secret: str) -> APIKeyWithSecret:
        ...
    


class Session(pydantic.BaseModel):
    """
    This related to refresh tokens, which have a session uuid ("sid") claim.

    When the client attempts to use a refresh token, we first check
    here to ensure that the "session", which is associated with a chain
    of refresh tokens that came from a single authentication, are still valid.
    """
    model_config = ...
    uuid: uuid.UUID
    expiration_time: datetime
    revoked: bool
    state: Optional[Dict[Any, Any]]
    @classmethod
    def from_orm(cls, orm: tiled.authn_database.orm.Session) -> Session:
        ...
    


class Principal(pydantic.BaseModel):
    "Represents a User or Service"
    model_config = ...
    uuid: uuid.UUID
    type: PrincipalType
    identities: List[Identity] = ...
    roles: List[Role] = ...
    api_keys: List[APIKey] = ...
    sessions: List[Session] = ...
    latest_activity: Optional[datetime] = ...
    access_token: Optional[SecretStr] = ...
    @classmethod
    def from_orm(cls, orm: tiled.authn_database.orm.Principal, latest_activity: Optional[datetime] = ...) -> Principal:
        ...
    


class APIKeyRequestParams(pydantic.BaseModel):
    expires_in: Optional[int] = ...
    access_tags: Optional[List[str]] = ...
    scopes: Optional[List[str]] = ...
    note: Optional[str] = ...


class PostMetadataRequest(pydantic.BaseModel):
    id: Optional[str] = ...
    structure_family: StructureFamily
    metadata: Dict = ...
    data_sources: List[DataSource] = ...
    specs: Specs = ...
    access_blob: Optional[Dict] = ...
    @pydantic.field_validator("specs")
    def specs_uniqueness_validator(cls, v): # -> None:
        ...
    
    @pydantic.model_validator(mode="after")
    def narrow_structure_type(self): # -> Self:
        "Convert the structure on each data_source from a dict to the appropriate pydantic model."
        ...
    


class PutDataSourceRequest(pydantic.BaseModel):
    data_source: DataSource
    ...


class PostMetadataResponse(pydantic.BaseModel, Generic[ResourceLinksT]):
    id: str
    links: Union[ArrayLinks, DataFrameLinks, SparseLinks]
    metadata: Dict
    data_sources: List[DataSource]
    access_blob: Dict
    ...


class PutMetadataResponse(pydantic.BaseModel, Generic[ResourceLinksT]):
    id: str
    links: Union[ArrayLinks, DataFrameLinks, SparseLinks]
    metadata: Optional[Dict] = ...
    data_sources: Optional[List[DataSource]] = ...
    access_blob: Optional[Dict] = ...


class DistinctValueInfo(pydantic.BaseModel):
    value: Any = ...
    count: Optional[int] = ...


class GetDistinctResponse(pydantic.BaseModel):
    metadata: Optional[Dict[str, List[DistinctValueInfo]]] = ...
    structure_families: Optional[List[DistinctValueInfo]] = ...
    specs: Optional[List[DistinctValueInfo]] = ...


class PutMetadataRequest(pydantic.BaseModel):
    metadata: Optional[Dict] = ...
    specs: Optional[Specs] = ...
    access_blob: Optional[Dict] = ...
    @pydantic.field_validator("specs")
    def specs_uniqueness_validator(cls, v): # -> None:
        ...
    


def JSONPatchType(dtype=...): # -> type[JSONPatchType]:
    ...

JSONPatchSpec = ...
JSONPatchAny = ...
class HyphenizedBaseModel(pydantic.BaseModel):
    model_config = ...


class PatchMetadataRequest(HyphenizedBaseModel):
    content_type: str
    metadata: Optional[Union[List[JSONPatchAny], Dict]] = ...
    specs: Optional[Union[Specs, List[JSONPatchSpec]]] = ...
    access_blob: Optional[Union[List[JSONPatchAny], Dict]] = ...
    @pydantic.field_validator("specs")
    def specs_uniqueness_validator(cls, v): # -> None:
        ...
    


class PatchMetadataResponse(pydantic.BaseModel, Generic[ResourceLinksT]):
    id: str
    links: Union[ArrayLinks, DataFrameLinks, SparseLinks]
    metadata: Optional[Dict]
    data_sources: Optional[List[DataSource]]
    access_blob: Optional[Dict]
    ...


SearchResponse = Response[List[Resource[NodeAttributes, Dict, Dict]], PaginationLinks, Dict]
class EnvelopeFormat(str, enum.Enum):
    json = ...
    msgpack = ...
