"""
This type stub file was generated by pyright.
"""

import contextlib
import pathlib
import uvicorn
from typing import Optional, Union

class ThreadedServer(uvicorn.Server):
    def install_signal_handlers(self): # -> None:
        ...
    
    @contextlib.contextmanager
    def run_in_thread(self): # -> Generator[str, Any, None]:
        ...
    


class SimpleTiledServer:
    """
    Run a simple Tiled server on a background thread.

    This is intended to be used for tutorials and development. It employs only
    basic security and should not be used to store anything important. It does
    not scale to large number of users. By default, it uses temporary storage.

    Parameters
    ----------
    directory : Optional[Path, str]
        Location where data, including files and embedded databases, will be
        stored. By default, a temporary directory will be used.
    api_key : Optional[str]
        By default, an 8-bit random secret is generated. (Production Tiled
        servers use longer secrets.)
    port : Optional[int]
        Port the server will listen on. By default, a random free high port
        is allocated by the operating system.

    Examples
    --------

    Run a server and connect to it.

    >>> from tiled.server import SimpleTiledServer
    >>> from tiled.client import from_uri
    >>> ts = SimpleTiledServer()
    >>> client = from_uri(ts.uri)

    Locate server data, databases, and log files.

    >>> ts.directory

    Run a server with persistent storage that can be reused.

    >>> ts = SimpleTiledServer("my_data/")
    """
    def __init__(self, directory: Optional[Union[str, pathlib.Path]] = ..., api_key: Optional[str] = ..., port: int = ..., readable_storage: Optional[Union[str, pathlib.Path]] = ...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def close(self): # -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    
