"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, Protocol
from redis import asyncio as redis

logger = ...
def safe_json_dump(content): # -> bytes:
    """Additional handling for NDSlice serialization."""
    ...

class StreamingDatastore(Protocol):
    def __init__(self, settings: Dict[str, Any]) -> None:
        ...
    
    def client(self) -> Any:
        ...
    
    def make_ws_handler(self, websocket, formatter, uri, node_id, schema) -> Callable[[int], None]:
        ...
    
    async def incr_seq(self, node_id: str) -> int:
        ...
    
    async def set(self, node_id, sequence, metadata, payload=...) -> None:
        ...
    
    async def get(self, key, *fields) -> None:
        ...
    
    async def close(self, node_id) -> None:
        ...
    


_DATASTORES: Dict[str, type[StreamingDatastore]] = ...
def register_datastore(name: str): # -> Callable[..., type[StreamingDatastore]]:
    """Decorator to register a backend class"""
    ...

class StreamingCache:
    def __init__(self, cache_config: dict[str, Any]) -> None:
        ...
    
    async def incr_seq(self, node_id: str) -> int:
        ...
    
    async def set(self, node_id, sequence, metadata, payload=...): # -> None:
        ...
    
    @property
    def client(self): # -> Callable[[], Any]:
        ...
    
    async def close(self, node_id): # -> None:
        ...
    
    def make_ws_handler(self, websocket, formatter, uri, node_id, schema): # -> Callable[[int], None]:
        ...
    


class PubSub:
    """
    Lightweight in-process publish/subscribe mechanism for TTLCache backend.

    This class provides a simple pub/sub system for use within a single process,
    intended as a backend for streaming data (e.g., with TTLCache). It allows
    multiple subscribers to listen for messages on named topics.

    Subscribers are tracked using weak references to asyncio.Queue objects.
    When a subscriber is garbage collected or unsubscribed, its weak reference
    is automatically removed from the topic's subscriber set, ensuring that
    resources are cleaned up without manual intervention.

    Thread-safety: This class is NOT thread-safe and is intended for use within
    a single asyncio event loop (i.e., within a single thread).

    Comparison to Redis pub/sub:
        - This implementation is in-process only; it does not support
          cross-process or cross-machine communication.
        - It is lightweight and has no external dependencies beyond Python's
          standard library and asyncio.
        - Unlike Redis pub/sub, messages are only delivered to subscribers
          within the same process.
    """
    def __init__(self) -> None:
        ...
    
    async def publish(self, topic: str, message): # -> None:
        ...
    
    def subscribe(self, topic: str): # -> AsyncGenerator[Any, Any]:
        ...
    


@register_datastore("memory")
class TTLCacheDatastore(StreamingDatastore):
    """
    An in-memory, TTL-based streaming datastore for single-process deployments.

    This class provides a drop-in, in-memory alternative to the Redis-backed
    streaming datastore. It is intended for development, testing, or
    single-process production deployments where persistence and multi-process
    support are not required.

    Configuration:
        settings: dict with the following keys:
            - maxsize (int, optional): Maximum number of items to cache per node.
              Defaults to 1000.
            - seq_ttl (float): Time-to-live (in seconds) for sequence counters.
            - data_ttl (float): Time-to-live (in seconds) for data entries.

    Limitations:
        - Not suitable for multi-process or distributed deployments.
        - No persistence: all data is lost when the process exits.
        - Not safe for use with multiple server processes or workers.

    When to use:
        - Use this class for local development, testing, or simple single-process
          deployments where persistence and multi-process support are not needed.
        - For production or distributed deployments, use the Redis-backed
          StreamingDatastore instead.
    """
    def __init__(self, settings: Dict[str, Any]) -> None:
        ...
    
    @property
    def client(self): # -> Self:
        ...
    
    async def incr_seq(self, node_id: str) -> int:
        ...
    
    async def set(self, node_id, sequence, metadata, payload=...): # -> None:
        ...
    
    async def get(self, key, *fields): # -> list[None] | list[Any]:
        ...
    
    async def close(self, node_id: str): # -> None:
        ...
    
    def make_ws_handler(self, websocket, formatter, uri, node_id, schema): # -> Callable[..., CoroutineType[Any, Any, None]]:
        ...
    


@register_datastore("redis")
class RedisStreamingDatastore(StreamingDatastore):
    def __init__(self, settings: Dict[str, Any]) -> None:
        ...
    
    @property
    def client(self) -> redis.Redis:
        ...
    
    async def incr_seq(self, node_id: str) -> int:
        ...
    
    async def set(self, node_id, sequence, metadata, payload=...): # -> None:
        ...
    
    async def close(self, node_id): # -> None:
        ...
    
    async def get(self, key, *fields): # -> List[Any]:
        ...
    
    def make_ws_handler(self, websocket, formatter, uri, node_id, schema): # -> Callable[..., CoroutineType[Any, Any, None]]:
        ...
    
