"""
This type stub file was generated by pyright.
"""

import contextlib
from collections.abc import Generator
from typing import Any, Literal, Mapping, Optional, Sequence
from fastapi import Request, WebSocket
from starlette.types import Scope
from ..access_control.protocols import AccessPolicy
from ..server.schemas import Principal
from ..type_aliases import AccessTags, Scopes

EMPTY_NODE = ...
API_KEY_COOKIE_NAME = ...
API_KEY_QUERY_PARAMETER = ...
CSRF_COOKIE_NAME = ...
@contextlib.contextmanager
def record_timing(metrics: dict[str, Any], key: str) -> Generator[None]:
    """
    Set timings[key] equal to the run time (in milliseconds) of the context body.
    """
    ...

def get_root_url(request: Request) -> str:
    """
    URL at which the app is being server, including API and UI
    """
    ...

def get_root_url_websocket(websocket: WebSocket) -> str:
    ...

def get_base_url_websocket(websocket: WebSocket) -> str:
    ...

def get_base_url(request: Request) -> str:
    """
    Base URL for the API
    """
    ...

def get_zarr_url(request, version: Literal["v2", "v3"] = ...): # -> str:
    """
    Base URL for the Zarr API
    """
    ...

def get_root_url_low_level(request_headers: Mapping[str, str], scope: Scope) -> str:
    ...

async def filter_for_access(entry, access_policy: Optional[AccessPolicy], principal: Principal, authn_access_tags: Optional[AccessTags], authn_scopes: Scopes, scopes: Sequence[str], metrics: dict[str, Any]): # -> MapAdapter[Any]:
    ...
