"""
This type stub file was generated by pyright.
"""

from typing import Tuple
from fastapi import APIRouter

ZARR_BLOCK_SIZE = ...
ZARR_BYTE_ORDER = ...
ZARR_CODEC_SPEC = ...
zarr_codec = ...
def convert_chunks_for_zarr(tiled_chunks: Tuple[Tuple[int]]): # -> list[int]:
    """Convert full tiled/dask chunk specification into zarr format

    Zarr only accepts chunks of constant size along each dimension; this function
    finds a unique representation of (possibly variable-sized chunks) internal to
    Tiled ArrayAdapter in terms of zarr blocks.

    Zarr chunks must be at least of size 1, even for zero-dimensional arrays.
    """
    ...

def get_zarr_router_v2() -> APIRouter:
    ...

def get_zarr_router_v3() -> APIRouter:
    ...
