"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Dict, Optional

class CannotRefreshAuthentication(Exception):
    ...


class TiledAuth(httpx.Auth):
    def __init__(self, refresh_url, csrf_token, token_directory, client_id: Optional[str] = ...) -> None:
        ...
    
    def __getstate__(self): # -> tuple[Any, Any, Path | Any, SerializableLock | Any]:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    
    def sync_get_token(self, key, reload_from_disk=...): # -> str | None:
        ...
    
    def sync_set_token(self, key, value): # -> None:
        ...
    
    def sync_clear_token(self, key): # -> None:
        ...
    
    def sync_auth_flow(self, request, attempt=...): # -> Generator[Any | Request, Any, Any | None]:
        ...
    
    def sync_tokens(self, tokens: Dict[str, str]): # -> None:
        ...
    
    async def async_get_token(self, key):
        ...
    
    async def async_set_token(self, key, token):
        ...
    
    async def async_clear_token(self, key):
        ...
    
    async def async_auth_flow(self, request):
        ...
    


def build_refresh_request(refresh_url, refresh_token, csrf_token, client_id: Optional[str] = ...): # -> Request:
    ...
