"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Union
from tiled.client.context import Context
from ..structures.core import Spec
from ..utils import DictView, ListView

JSON_ITEM = Union[str, int, float, bool, Dict[str, "JSON_ITEM"], List["JSON_ITEM"]]
class MetadataRevisions:
    def __init__(self, context, link) -> None:
        ...
    
    def __len__(self):
        ...
    
    def __getitem__(self, item_): # -> None:
        ...
    
    def delete_revision(self, n): # -> None:
        ...
    


class BaseClient:
    URL_CHARACTER_LIMIT = ...
    def __init__(self, context: Context, *, item, structure_clients, structure=..., include_data_sources=...) -> None:
        ...
    
    def structure(self): # -> None:
        """
        Return a dataclass describing the structure of the data.
        """
        ...
    
    def login(self): # -> None:
        """
        Depending on the server's authentication method, this will prompt for username/password:

        >>> c.login()
        Username: USERNAME
        Password: <input is hidden>

        or prompt you to open a link in a web browser to login with a third party:

        >>> c.login()
        You have ... minutes visit this URL

        https://...

        and enter the code: XXXX-XXXX
        """
        ...
    
    def logout(self): # -> None:
        """
        Log out.

        This method is idempotent: if you are already logged out, it will do nothing.
        """
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def context(self): # -> Context:
        ...
    
    def refresh(self): # -> Self:
        ...
    
    @property
    def item(self): # -> Any:
        "JSON payload describing this item. Mostly for internal use."
        ...
    
    @property
    def metadata(self) -> DictView[str, JSON_ITEM]:
        "Metadata about this data source."
        ...
    
    @property
    def parent(self):
        "Returns a client for the parent of this node."
        ...
    
    def metadata_copy(self): # -> list[Any | list[Spec]]:
        """
        Generate a mutable copy of metadata, specs, and access_tags for
        validating metadata (useful with update_metadata())
        """
        ...
    
    @property
    def specs(self) -> ListView[Spec]:
        "List of specifications describing the structure of the metadata and/or data."
        ...
    
    @property
    def access_blob(self) -> DictView[str, JSON_ITEM]:
        "Authorization information about this node, in blob form"
        ...
    
    @property
    def uri(self):
        "Direct link to this entry"
        ...
    
    @property
    def path_parts(self): # -> Any:
        "Location of node in tree, given as list of path segments."
        ...
    
    @property
    def structure_family(self): # -> StructureFamily:
        "Quick access to this entry"
        ...
    
    def data_sources(self): # -> list[DataSource[Any]] | None:
        ...
    
    def include_data_sources(self): # -> Self:
        """
        Ensure that data source and asset information is fetched.

        If it has already been fetched, this is a no-op.
        """
        ...
    
    def new_variation(self, structure_clients=..., include_data_sources=..., structure=..., **kwargs): # -> Self:
        """
        This is intended primarily for internal use and use by subclasses.
        """
        ...
    
    def asset_manifest(self, data_sources): # -> dict[Any, Any]:
        """
        Return a manifest of the relative paths of the contents in each asset.

        This return a dictionary keyed on asset ID.
        Assets backed by a single file are mapped to None (no manifest).
        Asset backed by a directory of files are mapped to a list of relative paths.

        Parameters
        ----------
        data_sources : dict
            The value returned by ``.data_sources()``. This is passed in explicitly
            to avoid fetching it twice in common usages. It also enables passing in
            a subset of the data_sources of interest.
        """
        ...
    
    def raw_export(self, destination_directory=..., max_workers=...): # -> list[Any]:
        """
        Download the raw assets backing this node.

        This may produce a single file or a directory.

        Parameters
        ----------
        destination_directory : Path, optional
            Destination for downloaded assets. Default is current working directory
        max_workers : int, optional
            Number of parallel workers downloading data. Default is 4.

        Returns
        -------
        paths : List[Path]
            Filepaths of exported files
        """
        ...
    
    @property
    def formats(self): # -> list[Any]:
        "List formats that the server can export this data as."
        ...
    
    def update_metadata(self, metadata=..., specs=..., access_tags=..., *, drop_revision=...): # -> None:
        """
        EXPERIMENTAL: Update metadata via a `dict.update`- like interface.

        `update_metadata` is a user-friendly wrapper for `patch_metadata`.
        This is subject to change or removal without notice.

        Parameters
        ----------
        metadata : dict, optional
            User metadata. May be nested. Must contain only basic types
            (e.g. numbers, strings, lists, dicts) that are JSON-serializable.
        specs : List[str], optional
            List of names that are used to label that the data and/or metadata
            conform to some named standard specification.
        access_tags: List[str], optional
            Server-specific authZ tags in list form, used to confer access to the node.
        drop_revision : bool, optional
            Replace current version without saving current version as a revision.
            Use with caution.

        See Also
        --------
        patch_metadata
        replace_metadata

        Notes
        -----
        `update_metadata` constructs a JSON Patch (RFC6902) by comparing user updates
        to existing metadata. It uses a slight variation of JSON Merge Patch (RFC7386)
        as an intermediary to implement a python `dict.update`-like user-friendly
        interface, but with additional features like key deletion (see examples) and
        support for `None (null)` values.

        Examples
        --------

        Add or update a key-value pair at the top or a nested level

        >>> node.update_metadata({'key': new_value})
        >>> node.update_metadata({'top_key': {'nested_key': new_value}})

        Remove an existing key

        >>> from tiled.client.metadata_update import DELETE_KEY
        >>> node.update_metadata({'key_to_be_deleted': DELETE_KEY})

        Interactively update complex metadata using a copy of original structure
        (e.g., in iPython you may use tab completion to navigate nested metadata)

        >>> md = node.metadata_copy()[0]
        >>> md['L1_key']['L2_key']['L3_key'] = new_value  # use tab completion
        >>> md['unwanted_key'] = DELETE_KEY
        >>> node.update_metadata(metadata=md)  # Update the copy on the server
        """
        ...
    
    def build_metadata_patches(self, metadata=..., specs=..., access_tags=...): # -> tuple[Any | list[Any], Any | list[Any] | None, Any | None]:
        """
        Build valid JSON Patches (RFC6902) for metadata and metadata validation
        specs accepted by `patch_metadata`.

        Parameters
        ----------
        metadata : dict, optional
            User metadata. May be nested. Must contain only basic types
            (e.g. numbers, strings, lists, dicts) that are JSON-serializable.

        specs : list[Spec], optional
            Metadata validation specifications.

        access_tags: List[str], optional
            Server-specific authZ tags in list form, used to confer access to the node.

        Returns
        -------
        metadata_patch : list[dict]
            A JSON serializable object representing a valid JSON patch (RFC6902)
            for metadata.
        specs_patch : list[dict]
            A JSON serializable object representing a valid JSON patch (RFC6902)
            for metadata validation specifications.
        access_blob_patch : list[dict]
            A JSON serializable object representing a valid JSON patch (RFC6902)
            for access control fields that are stored in the access_blob.

        See Also
        --------
        patch_metadata
        update_metadata

        Notes
        -----
        `build_metadata_patch` constructs a JSON Patch (RFC6902) by comparing user updates
        to existing metadata/specs. It uses a slight variation of JSON Merge Patch (RFC7386)
        as an intermediary to implement a python `dict.update`-like user-friendly
        interface, but with additional features like key deletion (see examples) and
        support for `None (null)` values.

        Examples
        --------

        Build a patch for adding/updating a key-value pair at the top or a nested level

        >>> patches = node.build_metadata_patches({'key': new_value})
        >>> patches = node.build_metadata_patches({'top_key': {'nested_key': new_value}})

        Build patches for metadata and specs ("mp", "sp")

        >>> mp, sp = node.build_metadata_patches(metadata=metadata, specs=specs)

        Build a patch for removing an existing key

        >>> from tiled.client.metadata_update import DELETE_KEY
        >>> node.build_metadata_patches({'key_to_be_deleted': DELETE_KEY})

        Interactively build a patch for complex metadata (e.g., in iPython you may use
        tab completion to navigate nested metadata)

        >>> md = node.metadata_copy()[0]
        >>> md['L1_key']['L2_key']['L3_key'] = new_value  # use tab completion
        >>> md['unwanted_key'] = DELETE_KEY
        >>> node.build_metadata_patches(metadata=md)  # Generate the patch
        """
        ...
    
    def patch_metadata(self, metadata_patch=..., specs_patch=..., access_blob_patch=..., content_type=..., drop_revision=...): # -> None:
        """
        EXPERIMENTAL: Patch metadata using a JSON Patch (RFC6902).

        This is subject to change or removal without notice.

        Parameters
        ----------
        metadata_patch : List[dict], optional
            JSON-serializable patch to be applied to metadata
        specs_patch : List[dict], optional
            JSON-serializable patch to be applied to metadata validation
            specifications list
        access_blob_patch : List[dict], optional
            JSON-serializable patch to be applied to the access_blob
        content_type : str
            Mimetype of the patches. Acceptable values are:

            * "application/json-patch+json"
              (See https://datatracker.ietf.org/doc/html/rfc6902)
            * "application/merge-patch+json"
              (See https://datatracker.ietf.org/doc/html/rfc7386)
        drop_revision : bool, optional
            Replace current version without saving current version as a revision.
            Use with caution.

        See Also
        --------
        update_metadata
        replace_metadata
        """
        ...
    
    def replace_metadata(self, metadata=..., specs=..., access_tags=..., drop_revision=...): # -> None:
        """
        EXPERIMENTAL: Replace metadata entirely (see update_metadata).

        This is subject to change or removal without notice.

        Parameters
        ----------
        metadata : dict, optional
            User metadata. May be nested. Must contain only basic types
            (e.g. numbers, strings, lists, dicts) that are JSON-serializable.
        specs : List[str], optional
            List of names that are used to label that the data and/or metadata
            conform to some named standard specification.
        access_tags: List[str], optional
            Server-specific authZ tags in list form, used to confer access to the node.
        drop_revision : bool, optional
            Replace current version without saving current version as a revision.
            Use with caution.

        See Also
        --------
        update_metadata
        patch_metadata
        """
        ...
    
    @property
    def metadata_revisions(self): # -> MetadataRevisions:
        ...
    
    def delete(self, recursive: bool = ..., external_only: bool = ...) -> None:
        """Delete the node and its contents, if any.

        Parameters
        ----------
        recursive : bool, optional
            If True, descend into sub-nodes and delete their contents too.
            Defaults to False.
        external_only : bool, optional
            If True, only delete externally-managed data. Defaults to True.
        """
        ...
    
    def close_stream(self): # -> None:
        "Declare the end of a stream of writes to this node."
        ...
    
    def __dask_tokenize__(self): # -> tuple[type[Self], Any]:
        ...
    
