"""
This type stub file was generated by pyright.
"""

import enum
import typing as tp
import httpx
from .utils import TiledResponse

CACHE_DATABASE_SCHEMA_VERSION = ...
class CachedResponse(TiledResponse):
    ...


def get_cache_key(request: httpx.Request) -> str:
    """Get the cache key from a request.

    The cache key is the str request url.

    Args:
        request: httpx.Request

    Returns:
        str: httpx.Request.url
    """
    ...

def get_size(response, content=...): # -> int:
    ...

def dump(response, content=...): # -> tuple[Any, str, Any, bool, Any | None, int, float, Literal[0]]:
    ...

def load(row, request=...): # -> CachedResponse:
    ...

def with_thread_lock(fn): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """Makes sure the wrapper isn't accessed concurrently."""
    ...

class ThreadingMode(enum.IntEnum):
    """Threading mode used in the sqlite3 package.

    https://docs.python.org/3/library/sqlite3.html#sqlite3.threadsafety

    """
    SINGLE_THREAD = ...
    MULTI_THREAD = ...
    SERIALIZED = ...


class Cache:
    def __init__(self, filepath=..., capacity=..., max_item_size=..., readonly=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def write_safe(self): # -> bool:
        """Check that it is safe to write.

        SQLite is not threadsafe for concurrent _writes_ unless the
        underlying sqlite library was built with thread safety
        enabled. Even still, it may be a good idea to use a thread
        lock (``@with_thread_lock``) to prevent parallel writes.

        """
        ...
    
    def __getstate__(self): # -> tuple[Path | Any, int | Any, int | Any, bool | Any, SerializableLock | Any]:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    
    @property
    def readonly(self): # -> bool:
        "If True, cache be read but not updated."
        ...
    
    @property
    def filepath(self): # -> Path:
        "Filepath of SQLite database storing cache data"
        ...
    
    @property
    def capacity(self): # -> int:
        "Max capacity in bytes. Includes response bodies only."
        ...
    
    @capacity.setter
    def capacity(self, capacity): # -> None:
        ...
    
    @property
    def max_item_size(self): # -> int:
        "Max size of a response body eligible for caching."
        ...
    
    @max_item_size.setter
    def max_item_size(self, max_item_size): # -> None:
        ...
    
    @with_thread_lock
    def clear(self): # -> None:
        """
        Drop all entries from HTTP response cache.
        """
        ...
    
    @with_thread_lock
    def get(self, request: httpx.Request) -> tp.Optional[httpx.Response]:
        """Get cached response from Cache.

        We use the httpx.Request.url as key.

        Args:
            request: httpx.Request

        Returns:
            tp.Optional[httpx.Response]
        """
        ...
    
    @with_thread_lock
    def set(self, *, request: httpx.Request, response: httpx.Response, content: tp.Optional[bytes] = ...) -> None:
        """Set new response entry in cache.

        In case the response does not yet have a '_content' property, content should
        be provided in the optional 'content' kwarg (usually using a callback)

        Parameters
        ----------
        request: httpx.Request
        response: httpx.Response, to cache
        content (bytes, optional): Defaults to None, should be provided in case
            response that not have yet content.
        """
        ...
    
    @with_thread_lock
    def delete(self, request: httpx.Request) -> None:
        """Delete an entry from cache.

        Args:
            request: httpx.Request
        """
        ...
    
    def size(self): # -> Any | Literal[0]:
        "Size of response bodies in bytes (does not count headers and other auxiliary info)"
        ...
    
    def count(self): # -> Any | Literal[0]:
        "Number of responses cached"
        ...
    
    def close(self) -> None:
        """Close cache."""
        ...
    
