"""
This type stub file was generated by pyright.
"""

import typing as tp
import attr
import httpx
from datetime import datetime

"""
Adapted from https://raw.githubusercontent.com/obendidi/httpx-cache/main/httpx_cache/transport.py
in accordance with its BSD-3 license
"""
logger = ...
_PERMANENT_REDIRECT_STATUSES = ...
def parse_headers_date(headers_date: tp.Optional[str]) -> tp.Optional[datetime]:
    """Parse a 'Date' header and return it as an optional datetime object.

    If the 'Date' does not exist return None
    If there is an error using parsing return None

    Args:
        headers: httpx.Headers

    Returns:
        Optional[datetime]
    """
    ...

def parse_cache_control_headers(headers: httpx.Headers) -> tp.Dict[str, tp.Optional[int]]:
    """Parse cache-control headers.

    Args:
        headers: An instance of httpx headers.

    Returns:
        parsed cache-control headers as dict.
    """
    ...

@attr.s
class ByteStreamWrapper(httpx.ByteStream):
    """Wrapper around the stream object of an httpx.Response."""
    stream: httpx.ByteStream = ...
    callback: tp.Callable[[bytes], tp.Any] = ...
    content: bytearray = ...
    def close(self) -> None:
        """Close stream."""
        ...
    
    async def aclose(self) -> None:
        """Close async stream."""
        ...
    
    def __iter__(self) -> tp.Iterator[bytes]:
        """Iterate over the stream object and store it's chunks in a content.

        After the stream is completed call the callback with content as argument.
        """
        ...
    
    async def __aiter__(self) -> tp.AsyncIterator[bytes]:
        """Iterate over the async stream object and store it's chunks in a content.

        After the stream is completed call the async callback with content as argument.
        """
        ...
    


class CacheControl:
    """Cache controller for httpx-cache.

    Uses 'cache-contol' header direcrives for using/skipping cache.

    If no cache-control directive is set, the cache is used by default (except if there
    is an expires header in the response.)
    """
    def __init__(self, *, cacheable_methods: tp.Tuple[str, ...] = ..., cacheable_status_codes: tp.Tuple[int, ...] = ..., always_cache: bool = ...) -> None:
        ...
    
    def is_request_cacheable(self, request: httpx.Request) -> bool:
        """Checks if an httpx request has the necessary requirement to support caching.

        A request is cacheable if:

            - url is absolute
            - method is defined as cacheable (by default only GET methods are cached)
            - request has no 'no-cache' cache-control header directive
            - request has no 'max-age=0' cache-control header directive

        Args:
            request: httpx.Request

        Returns:
            True if request cacheable else False
        """
        ...
    
    def is_response_fresh(self, *, request: httpx.Request, response: httpx.Response) -> bool:
        """Checks whether a cached response is fresh or not.

        Args:
            request: httpx.Request
            response: httpx.Response

        Returns:
            True if request is fresh else False
        """
        ...
    
    def is_response_cacheable(self, *, request: httpx.Request, response: httpx.Response) -> bool:
        """Check if an httpx response is cacheable.

        A response is cacheable if:

            - response status_code is cacheable
            - request method is cacheable
            - One of:
                - always_cache is True
            OR:
                - Response has no 'no-store' cache-control header
                - Request has no 'no-store' cache-control header

        Args:
            request: httpx.Request
            response: httpx.Response

        Returns:
            whether response is cacheable or not.
        """
        ...
    
    def needs_revalidation(self, *, request: httpx.Request, response: httpx.Response) -> bool:
        ...
    
