"""
This type stub file was generated by pyright.
"""

import pathlib
import httpx
from typing import Optional, Union
from .context import Context

def from_uri(uri, structure_clients=..., *, cache=..., remember_me=..., username=..., auth_provider=..., api_key=..., verify=..., prompt_for_reauthentication=..., headers=..., timeout=..., include_data_sources=..., auth: Optional[httpx.Auth] = ...):
    """
    Connect to a Node on a local or remote server.

    Parameters
    ----------
    uri : str
        e.g. "http://localhost:8000"
    structure_clients : str or dict, optional
        Use "dask" for delayed data loading and "numpy" for immediate
        in-memory structures (e.g. normal numpy arrays, pandas
        DataFrames). For advanced use, provide dict mapping a
        structure_family or a spec to a client object.
    cache : Cache, optional
    remember_me : bool
        Next time, try to automatically authenticate using this session.
    username : str, optional
        DEPRECATED. Ignored, and issues a warning if passed.
    auth_provider : str, optional
        DEPRECATED. Ignored, and issues a warning if passed.
    api_key : str, optional
        API key based authentication.
    verify : bool, optional
        Verify SSL certifications. True by default. False is insecure,
        intended for development and testing only.
    prompt_for_reauthentication : bool, optional
        DEPRECATED. Ignored, and issue a warning if passed.
    headers : dict, optional
        Extra HTTP headers.
    timeout : httpx.Timeout, optional
        If None, use Tiled default settings.
        (To disable timeouts, use httpx.Timeout(None)).
    include_data_sources : bool, optional
        Default False. If True, fetch information about underlying data sources.
    auth : httpx.Auth, optional
        Custom authentication handler.
    """
    ...

def from_context(context: Context, structure_clients=..., node_path_parts=..., include_data_sources=..., remember_me=...):
    """
    Advanced: Connect to a Node using a custom instance of httpx.Client or httpx.AsyncClient.

    Parameters
    ----------
    context : tiled.client.context.Context
    structure_clients : str or dict, optional
        Use "dask" for delayed data loading and "numpy" for immediate
        in-memory structures (e.g. normal numpy arrays, pandas
        DataFrames). For advanced use, provide dict mapping a
        structure_family or a spec to a client object.
    """
    ...

def from_profile(name, structure_clients=..., **kwargs):
    """
    Build a Node based a 'profile' (a named configuration).

    List available profiles and the source filepaths from Python like:

    >>> from tiled.profiles import list_profiles
    >>> list_profiles()

    or from a CLI like:

    $ tiled profile list

    Or show the file contents like:

    >>> from tiled.profiles import load_profiles
    >>> load_profiles()

    or from a CLI like:

    $ tiled profile show PROFILE_NAME

    Any additional parameters override profile content. See from_uri for details.
    """
    ...

def simple(directory: Optional[Union[str, pathlib.Path]] = ..., api_key: Optional[str] = ..., port: int = ..., readable_storage: Optional[Union[str, pathlib.Path]] = ..., quiet: bool = ...):
    """
    Spawn a Tiled server on a background thread and connect to it.

    This is intended to be used for tutorials and development. It employs only
    basic security and should not be used to store anything important. It does
    not scale to large number of users. By default, it uses temporary storage.

    Parameters
    ----------
    directory : Optional[Path, str]
        Location where data, including files and embedded databases, will be
        stored. By default, a temporary directory will be used.
    api_key : Optional[str]
        By default, an 8-bit random secret is generated. (Production Tiled
        servers use longer secrets.)
    port : Optional[int]
        Port the server will listen on. By default, a random free high port
        is allocated by the operating system.
    quiet : bool
        Suppress printing the server URL. False by default.
    """
    ...

SERVERS = ...
