"""
This type stub file was generated by pyright.
"""

import collections
import collections.abc
import concurrent.futures
import pandas
import pyarrow
from typing import Any, Iterable, Optional, TYPE_CHECKING, Union
from ..utils import IndexersMixin, Sentinel
from .base import BaseClient
from .stream import ContainerSubscription

if TYPE_CHECKING:
    ...
class Container(BaseClient, collections.abc.Mapping, IndexersMixin):
    STRUCTURE_CLIENTS_FROM_ENTRYPOINTS = ...
    @classmethod
    def discover_clients_from_entrypoints(cls): # -> None:
        """
        Search the software environment for libraries that register structure clients.

        This is called once automatically the first time Node.from_uri
        is called. It is idempotent.
        """
        ...
    
    def __init__(self, context, *, item, structure_clients, queries=..., sorting=..., structure=..., include_data_sources=...) -> None:
        "This is not user-facing. Use Node.from_uri."
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def sorting(self): # -> list[tuple[Any, int]]:
        """
        The current sorting of this Node

        Given as a list of tuples where the first entry is the sorting key
        and the second entry indicates ASCENDING (or 1) or DESCENDING (or -1).
        """
        ...
    
    def new_variation(self, *, structure_clients=..., queries=..., sorting=..., **kwargs): # -> Self:
        """
        Create a copy of this Node, optionally varying some parameters.

        This is intended primarily for internal use and use by subclasses.
        """
        ...
    
    def __len__(self): # -> int | Any:
        ...
    
    def __length_hint__(self): # -> int:
        ...
    
    def __iter__(self, _ignore_inlined_contents=...): # -> Generator[Any, Any, Any | None]:
        ...
    
    def __getitem__(self, keys, _ignore_inlined_contents=...):
        ...
    
    def delete_contents(self, keys: Optional[Union[str, Iterable[str]]] = ..., recursive: bool = ..., external_only: bool = ...) -> Container:
        """Delete the contents of this Container.

        Parameters
        ----------
        keys : str or list of str
            The key(s) to delete. If a list, all keys in the list will be deleted.
            If None (default), delete all contents.
        recursive : bool, optional
            If True, descend into sub-containers and delete their contents too.
            Defaults to False.
        external_only : bool, optional
            If True, only delete externally-managed data. Defaults to True.
        """
        ...
    
    def keys(self): # -> KeysView:
        ...
    
    def values(self): # -> ValuesView:
        ...
    
    def items(self): # -> ItemsView:
        ...
    
    def search(self, query): # -> Self:
        """
        Make a Node with a subset of this Node's entries, filtered by query.

        Examples
        --------

        >>> from tiled.queries import FullText
        >>> tree.search(FullText("hello"))
        """
        ...
    
    def distinct(self, *metadata_keys, structure_families=..., specs=..., counts=...): # -> Any:
        """
        Get the unique values and optionally counts of metadata_keys,
        structure_families, and specs in this Node's entries

        Examples
        --------

        Query all the distinct values of a key.

        >>> tree.distinct("foo", counts=True)

        Query for multiple keys at once.

        >>> tree.distinct("foo", "bar", counts=True)
        """
        ...
    
    def sort(self, *sorting): # -> Self:
        """
        Make a Node with the same entries but sorted according to `sorting`.

        Examples
        --------

        Sort by "color" in ascending order, and then by "height" in descending order.

        >>> from tiled.client import ASCENDING, DESCENDING
        >>> tree.sort(("color", ASCENDING), ("height", DESCENDING))

        Note that ``1`` may be used as a synonym for ``ASCENDING``, and ``-1``
        may be used as a synonym for ``DESCENDING``.
        """
        ...
    
    def export(self, filepath, fields=..., *, format=...): # -> None:
        """
        Download metadata and data below this node in some format and write to a file.

        Parameters
        ----------
        file: str or buffer
            Filepath or writeable buffer.
        fields: List[str], optional
            Filter which items in this node to export.
        format : str, optional
            If format is None and `file` is a filepath, the format is inferred
            from the name, like 'table.h5' implies format="application/x-hdf5". The format
            may be given as a file extension ("h5") or a media type ("application/x-hdf5").

        Examples
        --------

        Export all.

        >>> a.export("everything.h5")

        """
        ...
    
    def new(self, structure_family, data_sources, *, key=..., metadata=..., specs=..., access_tags=...):
        """
        Create a new item within this Node.

        This is a low-level method. See high-level convenience methods listed below.

        See Also
        --------
        write_array
        write_table
        write_coo_array
        """
        ...
    
    _SUGGESTED_MAX_UPLOAD_SIZE = ...
    def create_container(self, key=..., *, metadata=..., specs=..., access_tags=...):
        """Create a new, empty container.

        Parameters
        ----------
        key : str, optional
            Key (name) for this new node. If None, the server will provide a unique key.
        metadata : dict, optional
            User metadata. May be nested. Must contain only basic types
            (e.g. numbers, strings, lists, dicts) that are JSON-serializable.
        specs : List[Spec], optional
            List of names that are used to label that the data and/or metadata
            conform to some named standard specification.
        access_tags: List[str], optional
            Server-specific authZ tags in list form, used to confer access to the node.

        """
        ...
    
    def write_array(self, array, *, key=..., metadata=..., dims=..., specs=..., access_tags=...):
        """
        EXPERIMENTAL: Write an array.

        Parameters
        ----------
        array : array-like
        key : str, optional
            Key (name) for this new node. If None, the server will provide a unique key.
        metadata : dict, optional
            User metadata. May be nested. Must contain only basic types
            (e.g. numbers, strings, lists, dicts) that are JSON-serializable.
        dims : List[str], optional
            A label for each dimension of the array.
        specs : List[Spec], optional
            List of names that are used to label that the data and/or metadata
            conform to some named standard specification.
        access_tags: List[str], optional
            Server-specific authZ tags in list form, used to confer access to the node.

        """
        ...
    
    def write_awkward(self, array, *, key=..., metadata=..., dims=..., specs=..., access_tags=...):
        """
        Write an AwkwardArray.

        Parameters
        ----------
        array: awkward.Array
        key : str, optional
            Key (name) for this new node. If None, the server will provide a unique key.
        metadata : dict, optional
            User metadata. May be nested. Must contain only basic types
            (e.g. numbers, strings, lists, dicts) that are JSON-serializable.
        dims : List[str], optional
            A label for each dimension of the array.
        specs : List[Spec], optional
            List of names that are used to label that the data and/or metadata
            conform to some named standard specification.
        access_tags: List[str], optional
            Server-specific authZ tags in list form, used to confer access to the node.
        """
        ...
    
    def write_sparse(self, coords, data, shape, *, key=..., metadata=..., dims=..., specs=..., access_tags=...):
        """
        EXPERIMENTAL: Write a sparse array.

        Parameters
        ----------
        coords : array-like
        data : array-like
        shape : tuple
        key : str, optional
            Key (name) for this new node. If None, the server will provide a unique key.
        metadata : dict, optional
            User metadata. May be nested. Must contain only basic types
            (e.g. numbers, strings, lists, dicts) that are JSON-serializable.
        dims : List[str], optional
            A label for each dimension of the array.
        specs : List[Spec], optional
            List of names that are used to label that the data and/or metadata
            conform to some named standard specification.
        access_tags: List[str], optional
            Server-specific authZ tags in list form, used to confer access to the node.

        Examples
        --------

        Write a sparse.COO array.

        >>> import sparse
        >>> from numpy import array
        >>> coo = sparse.COO(coords=array([[2, 5]]), data=array([1.3, 7.5]), shape=(10,))
        >>> c.write_sparse(coords=coo.coords, data=coo.data, shape=coo.shape)

        This only supports a single chunk. For chunked upload, use lower-level methods.

        # Define the overall shape and the dimensions of each chunk.
        >>> from tiled.structures.sparse import COOStructure
        >>> structure = COOStructure(shape=(10,), chunks=((5, 5),))
        >>> data_source = DataSource(structure=structure, structure_family=StructureFamily.sparse)
        >>> x = c.new("sparse", [data_source])
        # Upload the data in each chunk.
        # Coords are given with in the reference frame of each chunk.
        >>> x.write_block(coords=array([[2, 4]]), data=array([3.1, 2.8]), block=(0,))
        >>> x.write_block(coords=array([[0, 1]]), data=array([6.7, 1.2]), block=(1,))
        """
        ...
    
    def create_appendable_table(self, schema: pyarrow.Schema, npartitions: int = ..., *, key=..., metadata=..., specs=..., access_tags=..., table_name: Optional[str] = ...):
        """Initialize a table whose rows can be appended to a partition.

        Parameters
        ----------
        schema : column names and dtypes info in the form of pyarrow.Schema
        npartitions : int, optional
            Number of partitions to create. Default is 1.
        key : str, optional
            Key (name) for this new node. If None, the server will provide a unique key.
        metadata : dict, optional
            User metadata. May be nested. Must contain only basic types
            (e.g. numbers, strings, lists, dicts) that are JSON-serializable.
        specs : List[Spec], optional
            List of names that are used to label that the data and/or metadata
            conform to some named standard specification.
        access_tags: List[str], optional
            Server-specific authZ tags in list form, used to confer access to the node.
        table_name : str, optional
            Optionally provide a name for the SQL table this should be stored in.
            By default a name unique to the schema will be chosen.

        See Also
        --------
        write_table
        """
        ...
    
    def write_table(self, data: Union[pandas.DataFrame, dict[str, Any]], *, key=..., metadata=..., specs=..., access_tags=...):
        """Write tabular data.

        The created asset will be stored as an external file (e.g. Parquet), which means
        the table can not be appended to in the future. To create a table that can be grown,
        use the `create_appendable_table` method instead.

        Parameters
        ----------
        data : pandas.DataFrame or dict
        key : str, optional
            Key (name) for this new node. If None, the server will provide a unique key.
        metadata : dict, optional
            User metadata. May be nested. Must contain only basic types
            (e.g. numbers, strings, lists, dicts) that are JSON-serializable.
        specs : List[Spec], optional
            List of names that are used to label that the data and/or metadata
            conform to some named standard specification.
        access_tags: List[str], optional
            Server-specific authZ tags in list form, used to confer access to the node.

        See Also
        --------
        create_appendable_table
        """
        ...
    
    def write_dataframe(self, data, *, key=..., metadata=..., specs=..., access_tags=...):
        ...
    
    def subscribe(self, executor: Optional[concurrent.futures.Executor] = ...) -> ContainerSubscription:
        """
        Subscribe to streaming updates about this container.

        Parameters
        ----------
        executor : concurrent.futures.Executor, optional
            Launches tasks asynchronously, in response to updates. By default,
            a concurrent.futures.ThreadPoolExecutor is used.

        Returns
        -------
        subscription : ContainerSubscription
        """
        ...
    


LENGTH_CACHE_TTL = ...
class Ascending(Sentinel):
    "Intended for more readable sorting operations. An alias for 1."
    def __index__(self): # -> Literal[1]:
        ...
    


class Descending(Sentinel):
    "Intended for more readable sorting operations. An alias for -1."
    def __index__(self): # -> Literal[-1]:
        ...
    


ASCENDING = ...
DESCENDING = ...
class _LazyLoad:
    def __init__(self, import_module_args, attr_name) -> None:
        ...
    
    def __call__(self): # -> Any:
        ...
    


class _Wrap:
    def __init__(self, obj) -> None:
        ...
    
    def __call__(self): # -> Any:
        ...
    


DEFAULT_STRUCTURE_CLIENT_DISPATCH = ...
