"""
This type stub file was generated by pyright.
"""

from typing import List, Literal, Optional
from tiled.schemas import AboutAuthenticationProvider
from ..utils import DictView

USER_AGENT = ...
API_KEY_AUTH_HEADER_PATTERN = ...
def raise_if_cannot_prompt(): # -> None:
    ...

def identity_provider_input(providers: List[AboutAuthenticationProvider]) -> AboutAuthenticationProvider:
    ...

def username_input(): # -> str:
    ...

def password_input(): # -> str:
    ...

class PasswordRejected(RuntimeError):
    ...


def prompt_for_credentials(http_client, providers: List[AboutAuthenticationProvider]):
    """
    Prompt for credentials or third-party login at an interactive terminal.
    """
    ...

class Context:
    """
    Wrap an httpx.Client with an optional cache and authentication functionality.
    """
    def __init__(self, uri, *, headers=..., api_key=..., cache=..., timeout=..., verify=..., app=..., raise_server_exceptions=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    def __getstate__(self): # -> tuple[str, URL | Any, Headers, list[Cookie], Timeout, Auth | None, bool | Any, Path | Any, About, Any]:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    
    @classmethod
    def from_any_uri(cls, uri, *, headers=..., api_key=..., cache=..., timeout=..., verify=..., app=...): # -> tuple[Self, list[Any]]:
        """
        Accept a URI to a specific node.

        For example, given URI "https://example.com/api/v1//metadata/a/b/c"
        return a Context connected to "https://examples/api/v1" and the list
        ["a", "b", "c"].
        """
        ...
    
    @classmethod
    def from_app(cls, app, *, cache=..., headers=..., timeout=..., api_key=..., raise_server_exceptions=..., uri=...): # -> Self:
        """
        Construct a Context around a FastAPI app. Primarily for testing.
        """
        ...
    
    @property
    def tokens(self) -> DictView[Literal["access_token", "refresh_token"], str]:
        "A view of the current access and refresh tokens."
        ...
    
    @property
    def api_key(self): # -> str | Any | None:
        ...
    
    @api_key.setter
    def api_key(self, api_key): # -> None:
        ...
    
    @property
    def cache(self):
        ...
    
    @cache.setter
    def cache(self, cache): # -> None:
        ...
    
    def which_api_key(self): # -> Any | None:
        """
        A 'who am I' for API keys
        """
        ...
    
    def create_api_key(self, scopes=..., expires_in=..., note=..., access_tags=...): # -> Any | None:
        """
        Generate a new API key.

        Users with administrative scopes may use ``Context.admin.revoke_api_key``
        to create API keys on behalf of other users or services.

        Parameters
        ----------
        scopes : Optional[List[str]]
            Restrict the access available to the API key by listing specific scopes.
            By default, this will have the same access as the user.
        expires_in : Optional[Union[int, str]]
            Number of seconds until API key expires, given as integer seconds
            or a string like: '3y' (years), '3d' (days), '5m' (minutes), '1h'
            (hours), '30s' (seconds). If None, it will never expire or it will
            have the maximum lifetime allowed by the server.
        note : Optional[str]
            Description (for humans).
        access_tags : Optional[List[str]]
            Restrict the access available to the API key by listing specific tags.
            By default, this will have no limits on access tags.
        """
        ...
    
    def revoke_api_key(self, first_eight): # -> None:
        """
        Revoke an API key.

        The API key must belong to the currently-authenticated user or service.
        Users with administrative scopes may use ``Context.admin.revoke_api_key``
        to revoke API keys belonging to other users.

        Parameters
        ----------
        first_eight : str
            Identify the API key to be deleted by passing its first 8 characters.
            (Any additional characters passed will be truncated.)
        """
        ...
    
    @property
    def app(self): # -> ASGI3App | _WrapASGI2:
        ...
    
    @property
    def base_url(self): # -> URL:
        ...
    
    @property
    def event_hooks(self): # -> dict[str, list[EventHook]]:
        "httpx.Client event hooks. This is exposed for testing."
        ...
    
    def authenticate(self, *, remember_me=...): # -> None:
        """
        Log in to a Tiled server.

        Depending on the server's authentication method, this will prompt for username/password:

        >>> c.login()
        Username: USERNAME
        Password: <input is hidden>

        or prompt you to open a link in a web browser to login with a third party:

        >>> c.login()
        You have ... minutes to visit this URL

        https://...

        and enter the code: XXXX-XXXX

        Parameters
        ----------
        remember_me : bool
            Next time, try to automatically authenticate using this session.
        """
        ...
    
    login = ...
    def configure_auth(self, tokens, remember_me=...): # -> None:
        """
        Configure Tiled client with tokens for refresh flow.

        Parameters
        ----------
        tokens : dict, optional
            Must include keys 'access_token' and 'refresh_token'
        """
        ...
    
    @property
    def authenticated(self) -> bool:
        """
        Boolean indicated whether session is authenticated (true) or anonymous (false)

        Examples
        --------

        An anonymous session at first, after login, is authenticated.

        >>> client.context.authenticated
        False
        >>> client.login()
        Username: USERNAME
        Password: <input is hidden>
        >>> client.context.authenticated
        True

        """
        ...
    
    def use_cached_tokens(self): # -> bool:
        """
        Attempt to reconnect using cached tokens.

        Returns
        -------
        success : bool
            Indicating whether valid cached tokens were found
        """
        ...
    
    def force_auth_refresh(self): # -> Any:
        """
        Execute refresh flow.

        This method is exposed for testing and debugging uses.

        It should never be necessary for the user to call. Refresh flow is
        automatically executed by tiled.client.auth.TiledAuth when the current
        access_token expires.
        """
        ...
    
    def whoami(self): # -> Any | None:
        "Return information about the currently-authenticated user or service."
        ...
    
    def logout(self): # -> None:
        """
        Log out of the current session (if any).

        This method is idempotent.
        """
        ...
    
    def revoke_session(self, session_id): # -> None:
        """
        Revoke a Session so it cannot be refreshed.

        This may be done to ensure that a possibly-leaked refresh token cannot be used.
        """
        ...
    


class Admin:
    "Accessor for requests that require administrative privileges."
    def __init__(self, context: Context) -> None:
        ...
    
    def list_principals(self, offset=..., limit=...): # -> Any | None:
        "List Principals (users and services) in the authentication database."
        ...
    
    def show_principal(self, uuid): # -> Any | None:
        "Show one Principal (user or service) in the authentication database."
        ...
    
    def create_api_key(self, uuid, scopes=..., expires_in=..., note=..., access_tags=...): # -> Any | None:
        """
        Generate a new API key for another user or service.

        Parameters
        ----------
        uuid : str
            Identify the principal -- the user or service
        scopes : Optional[List[str]]
            Restrict the access available to the API key by listing specific scopes.
            By default, this will have the same access as the principal.
        expires_in : Optional[int]
            Number of seconds until API key expires. If None,
            it will never expire or it will have the maximum lifetime
            allowed by the server.
        note : Optional[str]
            Description (for humans).
        access_tags : Optional[List[str]]
            Restrict the access available to the API key by listing specific tags.
            By default, this will have no limits on access tags.
        """
        ...
    
    def create_service_principal(self, role): # -> Any | None:
        """
        Generate a new service principal.

        Parameters
        ----------
        role : str
            Specify the role (e.g. user or admin)
        """
        ...
    
    def revoke_api_key(self, uuid, first_eight=...): # -> Response | None:
        """
        Revoke an API key belonging to any user or service.

        Parameters
        ----------
        uuid : str
            Identify the principal whose API key will be deleted. This is
            required in order to reduce the chance of accidentally revoking
            the wrong key.
        first_eight : str
            Identify the API key to be deleted by passing its first 8 characters.
            (Any additional characters passed will be truncated.)
        """
        ...
    


class CannotPrompt(Exception):
    ...


def password_grant(http_client, auth_endpoint, provider, username, password):
    ...

def device_code_grant(http_client, auth_endpoint: str, client_id: Optional[str], token_endpoint: Optional[str], scopes: str = ...):
    ...
