"""
This type stub file was generated by pyright.
"""

from ..utils import modules_available

if modules_available("blosc2"):
    class Blosc2Decoder:
        def __init__(self) -> None:
            ...
        
        def decode(self, data: bytes) -> bytes:
            ...
        
        def flush(self) -> bytes:
            ...
        
    
    
if modules_available("zstandard"):
    class ZStandardDecoder:
        def __init__(self) -> None:
            ...
        
        def decode(self, data: bytes) -> bytes:
            ...
        
        def flush(self) -> bytes:
            ...
        
    
    
