"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Iterable

"Download utilities implemented using httpx and rich progress bars, with parallelism."
CONTENT_DISPOSITION_PATTERN = ...
ATTACHMENT_FILENAME_PLACEHOLDER = ...
def download(client, urls: Iterable[str], paths: Iterable[Path], *, max_workers: int = ...): # -> list[Any]:
    """
    Download multiple URLs to given paths, in parallel.
    """
    ...
