"""
This type stub file was generated by pyright.
"""

import contextlib
import logging

TILED_LOG_AUTH_TOKEN = ...
class ClientLogRecord(logging.LogRecord):
    def getMessage(self): # -> str:
        ...
    


def patched_make_record(name, level, fn, lno, msg, args, exc_info, func=..., extra=..., sinfo=...): # -> ClientLogRecord:
    ...

logger = ...
handler = ...
log_format = ...
def log_request(request): # -> None:
    ...

def log_response(response): # -> None:
    ...

def collect_request(request): # -> None:
    ...

def collect_response(response): # -> None:
    ...

def show_logs(): # -> None:
    """
    Log network traffic and interactions with the cache.

    This is just a convenience function that makes some Python logging configuration calls.
    """
    ...

def hide_logs(): # -> None:
    """
    Undo show_logs().
    """
    ...

History = ...
_history = ...
@contextlib.contextmanager
def record_history(): # -> Generator[History, Any, None]:
    """
    Collect requests and responses.

    >>> with history() as t:
    ...     ...
    ...

    >>> t.requests
    [...]

    >>> t.responses
    [...]
    """
    ...
