"""
This type stub file was generated by pyright.
"""

import abc
import concurrent.futures
import sys
import httpx
from typing import Callable, Generic, List, Optional, Self, TypeVar
from ..client.base import BaseClient
from ..stream_messages import ArrayData, ArrayRef, ChildCreated, ChildMetadataUpdated, Schema, TableData, Update
from .context import Context

if sys.version_info >= (3, 11):
    ...
else:
    ...
T = TypeVar("T")
Callback = Callable[[T], None]
API_KEY_LIFETIME = ...
RECEIVE_TIMEOUT = ...
logger = ...
__all__ = ["Subscription"]
class _TestClientWebsocketWrapper:
    """Wrapper for TestClient websockets."""
    def __init__(self, http_client, uri: httpx.URL) -> None:
        ...
    
    def connect(self, api_key: Optional[str], start: Optional[int] = ..., max_size: int = ...): # -> None:
        """Connect to the websocket."""
        ...
    
    def recv(self, timeout=...): # -> None:
        """Receive data from websocket with consistent interface."""
        ...
    
    def close(self): # -> None:
        """Close websocket connection."""
        ...
    


class _RegularWebsocketWrapper:
    """Wrapper for regular websockets."""
    def __init__(self, http_client, uri: httpx.URL) -> None:
        ...
    
    def connect(self, api_key: Optional[str], start: Optional[int] = ..., max_size: int = ...): # -> None:
        """Connect to the websocket."""
        ...
    
    def recv(self, timeout=...): # -> Data | None:
        """Receive data from websocket with consistent interface."""
        ...
    
    def close(self): # -> None:
        """Close websocket connection."""
        ...
    


class CallbackRegistry(Generic[T]):
    """
    Distribute updates to user-provided callback functions.

    Parameters
    ----------

    executor : concurrent.futures.Executor
        Launches tasks asynchronously, in response to updates
    """
    def __init__(self, executor: concurrent.futures.Executor) -> None:
        ...
    
    @property
    def executor(self): # -> Executor:
        ...
    
    def process(self, update: T): # -> None:
        "Fan an update out to all registered callbacks."
        ...
    
    def add_callback(self, callback: Callback[T]) -> Self:
        """
        Register a callback to be run when the Subscription receives an update.

        The callback registry only holds a weak reference to the callback. If
        no hard references are held elsewhere in the program, the callback will
        be silently removed.

        Parameters
        ----------
        callback : Callback

        Returns
        -------
        Subscription

        Examples
        --------

        Simply subscribe the print function.

        >>> sub.add_callback(print)

        Subscribe a custom function.

        >>> def f(sub, data):
                ...

        >>> sub.add_callback(f)

        Start receiving updates, beginning with the next one.

        >>> sub.start()

        Or start receiving updates beginning as far back as the server has
        available.

        >>> sub.start(0)

        Or start receiving updates beginning with a specific sequence number.

        >>> sub.start(3)

        The method calls can be chained like:

        >>> sub.add_callback(f).add_callback(g).start()

        """
        ...
    
    def remove_callback(self, callback: Callback[T]) -> Self:
        """
        Unregister a callback.

        Parameters
        ----------
        callback : Callback

        Returns
        -------
        Subscription
        """
        ...
    


class Subscription(abc.ABC):
    """
    Subscribe to streaming updates from a node.

    Parameters
    ----------
    context : tiled.client.Context
        Provides connection to Tiled server
    segments : list[str]
        Path to node of interest, given as a list of path segments
    executor : concurrent.futures.Executor, optional
        Launches tasks asynchronously, in response to updates. By default,
        a concurrent.futures.ThreadPoolExecutor is used.
    """
    def __init__(self, context: Context, segments: List[str] = ..., executor: Optional[concurrent.futures.Executor] = ...) -> None:
        ...
    
    @property
    def executor(self): # -> Executor | ThreadPoolExecutor:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def context(self) -> Context:
        ...
    
    @property
    def segments(self) -> List[str]:
        ...
    
    @abc.abstractmethod
    def process(self, *args) -> None:
        ...
    
    def start(self, start: Optional[int] = ..., max_size: int = ...) -> None:
        """
        Connect to the websocket, and block while receiving and processing updates.

        Parameters
        ----------
        start : int, optional
            By default, the stream begins from the most recent update. Use this
            parameter to replay from some earlier update. Use 1 to start from
            the first item, 0 to start from as far back as available (which may
            be later than the first item), or any positive integer to start
            from a specific point in the sequence.
        max_size : int, optional
            Maximum size in bytes for incoming WebSocket messages. Default is 1 MB.
            Increase this if you expect to receive large messages.

        Examples
        --------

        Starting the Subscription blocks the current thread. Use Ctrl+C to interrupt.

        >>> sub.start()

        Start with a larger max message size.

        >>> sub.start(max_size=10_000_000)

        """
        ...
    
    def start_in_thread(self, start: Optional[int] = ..., max_size: int = ...) -> Self:
        """
        Start a thread to connect to the websocket and receive updates.

        Parameters
        ----------
        start : int, optional
            By default, the stream begins from the most recent update. Use this
            parameter to replay from some earlier update. Use 1 to start from
            the first item, 0 to start from as far back as available (which may
            be later than the first item), or any positive integer to start
            from a specific point in the sequence.
        max_size : int, optional
            Maximum size in bytes for incoming WebSocket messages. Default is 1 MB.
            Increase this if you expect to receive large messages.

        Examples
        --------

        Starting the Subscription starts a thread that connects and receives updates.

        >>> sub.start_in_thread()

        Start with a larger max message size.

        >>> sub.start_in_thread(max_size=10_000_000)

        To stop the thread:

        >>> sub.disconnect()


        """
        ...
    
    def disconnect(self, wait=...) -> None:
        "Close the websocket connection."
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    


class ContainerSubscription(Subscription):
    """
    Subscribe to streaming updates from a container.

    Parameters
    ----------
    context : tiled.client.Context
        Provides connection to Tiled server
    segments : list[str]
        Path to node of interest, given as a list of path segments
    executor : concurrent.futures.Executor, optional
        Launches tasks asynchronously, in response to updates. By default,
        a concurrent.futures.ThreadPoolExecutor is used.
    structure_clients : dict
    """
    def __init__(self, context: Context, segments: List[str] = ..., executor: Optional[concurrent.futures.Executor] = ..., structure_clients: dict = ...) -> None:
        ...
    
    def process(self, update: Update): # -> None:
        ...
    


class ArraySubscription(Subscription):
    """
    Subscribe to streaming updates from an array.

    Parameters
    ----------
    context : tiled.client.Context
        Provides connection to Tiled server
    segments : list[str]
        Path to node of interest, given as a list of path segments
    executor : concurrent.futures.Executor, optional
        Launches tasks asynchronously, in response to updates. By default,
        a concurrent.futures.ThreadPoolExecutor is used.
    """
    def __init__(self, context: Context, segments: List[str] = ..., executor: Optional[concurrent.futures.Executor] = ...) -> None:
        ...
    
    def process(self, update: Update): # -> None:
        ...
    


class TableSubscription(Subscription):
    """
    Subscribe to streaming updates from an table.

    Parameters
    ----------
    context : tiled.client.Context
        Provides connection to Tiled server
    segments : list[str]
        Path to node of interest, given as a list of path segments
    executor : concurrent.futures.Executor, optional
        Launches tasks asynchronously, in response to updates. By default,
        a concurrent.futures.ThreadPoolExecutor is used.
    """
    def __init__(self, context: Context, segments: List[str] = ..., executor: Optional[concurrent.futures.Executor] = ...) -> None:
        ...
    
    def process(self, update: Update): # -> None:
        ...
    


class UnparseableMessage(RuntimeError):
    "Message can be decoded but cannot be interpreted by the application"
    ...


def parse_schema(data: bytes) -> Schema:
    "Parse msgpack-encoded bytes into a Schema model."
    ...

def parse_update(subscription: Subscription, data: bytes, schema: Schema) -> Update:
    "Parse msgpack-encoded bytes into an Update model."
    ...

class LiveChildCreated(ChildCreated):
    model_config = ...
    subscription: ContainerSubscription
    def child(self) -> BaseClient:
        "Construct a client object for the newly-created child."
        ...
    
    @property
    def uri(self) -> str:
        "The URI to the newly-created child"
        ...
    


class LiveChildMetadataUpdated(ChildMetadataUpdated):
    model_config = ...
    subscription: ContainerSubscription


class LiveArrayData(ArrayData):
    model_config = ...
    subscription: ArraySubscription
    def data(self):
        "Decode array"
        ...
    


class LiveArrayRef(ArrayRef):
    model_config = ...
    subscription: ArraySubscription
    def data(self): # -> ndarray[tuple[int, ...], dtype[Any]]:
        "Fetch array"
        ...
    


class LiveTableData(TableData):
    model_config = ...
    subscription: TableSubscription
    def data(self):
        "Get table"
        ...
    


SCHEMA_MESSAGE_TYPES = ...
UPDATE_MESSAGE_TYPES = ...
