"""
This type stub file was generated by pyright.
"""

import typing as tp
import httpx
from .cache import Cache

"""
Adapted from https://raw.githubusercontent.com/obendidi/httpx-cache/main/httpx_cache/transport.py
in accordance with its BSD-3 license
"""
class Transport(httpx.BaseTransport):
    """Custom transport, implementing caching and custom compression encodings.

    Args:
        transport (optional): an existing httpx transport, if no transport
            is given, defaults to an httpx.HTTPTransport with default args.
        cache (optional): cache to use with this transport, defaults to
            httpx_cache.DictCache
        cacheable_methods: methods that are allowed to be cached, defaults to ['GET']
        cacheable_status_codes: status codes that are allowed to be cached,
            defaults to: (200, 203, 300, 301, 308)
    """
    def __init__(self, *, transport: tp.Optional[httpx.BaseTransport] = ..., cache: tp.Optional[Cache] = ..., cacheable_methods: tp.Tuple[str, ...] = ..., cacheable_status_codes: tp.Tuple[int, ...] = ..., always_cache: bool = ...) -> None:
        ...
    
    def close(self) -> None:
        ...
    
    def handle_request(self, request: httpx.Request) -> httpx.Response:
        ...
    
