"""
This type stub file was generated by pyright.
"""

import httpx
import stamina.instrumentation
from collections.abc import Hashable
from threading import Lock
from typing import Optional, Union
from ..structures.core import Spec

MSGPACK_MIME_TYPE = ...
def raise_for_status(response) -> None:
    """
    Raise the `httpx.HTTPStatusError` if one occurred. Include correlation ID.
    """
    ...

def handle_error(response): # -> None:
    ...

class ClientError(httpx.HTTPStatusError):
    def __init__(self, message, request, response) -> None:
        ...
    


def should_retry(exception: Exception) -> bool:
    ...

TILED_RETRY_ATTEMPTS = ...
TILED_RETRY_TIMEOUT = ...
TILED_DEVICE_FLOW_ATTEMPTS = ...
def retry_context(): # -> _RetryContextIterator:
    "Iterable that yields a context manager per retry attempt"
    ...

def should_poll_for_tokens(exception: Exception) -> bool:
    ...

def polling_retry_context(timeout: float): # -> _RetryContextIterator:
    ...

def init_retry_logging(log_level: int = ...) -> stamina.instrumentation.RetryHook:
    """
    Initialize logging using the standard library.

    Returned hook logs scheduled retries at *log_level*.

    .. versionadded:: 23.2.0
    """
    ...

LoggingOnRetryHook = ...
class TiledResponse(httpx.Response):
    def json(self): # -> Any:
        ...
    


class UnknownStructureFamily(KeyError):
    ...


def export_util(file, format, get, link, params): # -> None:
    """
    Download client data in some format and write to a file.

    This is used by the export method on clients. It intended for internal use.

    Parameters
    ----------
    file: str, Path, or buffer
        Filepath or writeable buffer.
    format : str, optional
        If format is None and `file` is a filepath, the format is inferred
        from the name, like 'table.csv' implies format="text/csv". The format
        may be given as a file extension ("csv") or a media type ("text/csv").
    get : callable
        Client's internal GET method
    link: str
        URL to download full data
    params : dict
        Additional parameters for the request, which may be used to subselect
        or slice, for example.
    """
    ...

def client_for_item(context, structure_clients, item, structure=..., include_data_sources=...):
    """
    Create an instance of the appropriate client class for an item.

    This is intended primarily for internal use and use by subclasses.
    """
    ...

DEFAULT_TIMEOUT_PARAMS = ...
def params_from_slice(slice): # -> dict[Any, Any]:
    "Generate URL query param ?slice=... from Python slice object."
    ...

class SerializableLock:
    """A Serializable per-process Lock

    Vendored from dask.utils because it is used parts of tiled that do not
    otherwise have a dask dependency.

    This wraps a normal ``threading.Lock`` object and satisfies the same
    interface.  However, this lock can also be serialized and sent to different
    processes.  It will not block concurrent operations between processes (for
    this you should look at ``multiprocessing.Lock`` or ``locket.lock_file``
    but will consistently deserialize into the same lock.
    So if we make a lock in one process::
        lock = SerializableLock()
    And then send it over to another process multiple times::
        bytes = pickle.dumps(lock)
        a = pickle.loads(bytes)
        b = pickle.loads(bytes)
    Then the deserialized objects will operate as though they were the same
    lock, and collide as appropriate.
    This is useful for consistently protecting resources on a per-process
    level.
    The creation of locks is itself not threadsafe.
    """
    _locks = ...
    token: Hashable
    lock: Lock
    def __init__(self, token=...) -> None:
        ...
    
    def acquire(self, *args, **kwargs): # -> bool:
        ...
    
    def release(self, *args, **kwargs): # -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    
    def locked(self): # -> bool:
        ...
    
    def __getstate__(self): # -> Hashable:
        ...
    
    def __setstate__(self, token): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...


def get_asset_filepaths(node): # -> list[Any]:
    """
    Given a node, return a list of filepaths of the data backing it.
    """
    ...

def chunks_repr(chunks: tuple[tuple[int, ...], ...]) -> str:
    """A human-friendly representation of the chunks spec

    Avoids printing long line of repeated values when representing chunks
    for large arrays.
    """
    ...

def normalize_specs(specs: Optional[Union[list[str], list[Spec], str]]) -> Optional[list[dict[str, str]]]:
    "Represent a list of Spec objects or strings as a list of dicts"
    ...
