"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Generic, Optional, Tuple, TypeVar
from pydantic import BaseModel, HttpUrl
from ..adapters.protocols import BaseAdapter
from ..server.schemas import Principal
from ..type_aliases import AccessBlob, AccessTags, Filters, Scopes
from .protocols import AccessPolicy

ALL_ACCESS = ...
NO_ACCESS = ...
logger = ...
handler = ...
log_level = ...
if log_level:
    ...
class DummyAccessPolicy(AccessPolicy):
    "Impose no access restrictions."
    async def init_node(self, principal: Principal, authn_access_tags: Optional[AccessTags], authn_scopes: Scopes, access_blob: Optional[AccessBlob] = ...) -> Tuple[bool, AccessBlob]:
        "Do nothing; there is no persistent state to initialize."
        ...
    
    async def allowed_scopes(self, node: BaseAdapter, principal: Principal, authn_access_tags: Optional[AccessTags], authn_scopes: Scopes) -> Scopes:
        "Always allow all scopes."
        ...
    
    async def filters(self, node: BaseAdapter, principal: Principal, authn_access_tags: Optional[AccessTags], authn_scopes: Scopes, scopes: Scopes) -> Filters:
        "Always impose no filtering on results."
        ...
    


class TagBasedAccessPolicy(AccessPolicy):
    def __init__(self, *, provider, tags_db, access_tags_parser, scopes=...) -> None:
        ...
    
    async def init_node(self, principal: Principal, authn_access_tags: Optional[AccessTags], authn_scopes: Scopes, access_blob: Optional[AccessBlob] = ...) -> Tuple[bool, AccessBlob]:
        ...
    
    async def modify_node(self, node: BaseAdapter, principal: Principal, authn_access_tags: Optional[AccessTags], authn_scopes: Scopes, access_blob: Optional[AccessBlob]) -> Tuple[bool, AccessBlob]:
        ...
    
    async def allowed_scopes(self, node: BaseAdapter, principal: Principal, authn_access_tags: Optional[AccessTags], authn_scopes: Scopes) -> Scopes:
        ...
    
    async def filters(self, node: BaseAdapter, principal: Principal, authn_access_tags: Optional[AccessTags], authn_scopes: Scopes, scopes: Scopes) -> Filters:
        ...
    


T = TypeVar("T")
class ResultHolder(BaseModel, Generic[T]):
    result: T
    ...


class ExternalPolicyDecisionPoint(AccessPolicy, ABC):
    def __init__(self, authorization_provider: HttpUrl, create_node_endpoint: str, allowed_tags_endpoint: str, scopes_endpoint: str, modify_node_endpoint: Optional[str] = ..., provider: Optional[str] = ..., empty_access_blob_public: Optional[bool] = ...) -> None:
        """
        Initialize an access policy configuration.

        Parameters
        ----------
        authorization_provider : HttpUrl
            The base URL of the authorization provider.
        create_node_endpoint : str
            An endpoint that returns a boolean decision on whether a use may create a node
        allowed_tags_endpoint : str
            An endpoint that returns a list[str] of tags a user may view on a node
        scopes_endpoint : str
            An endpoint that returns a set[str] of scopes a user has on a node
        modify_node_endpoint : str, optional
            An endpoint that returns a boolean decision on whether a use may modify a node
            Defaults to create_node_endpoint if not set
        provider : Optional[str], optional
            The name of the authorization provider, by default None.
        empty_access_blob_public: bool, optional
            Should a node (e.g. the root node) with no access_blob be treated as public,
            read/writable by any request with correct scopes? Default None, which does not
            short circuit the logic and lets the remote provider decide.
        empty_tag_list_include_all: bool, optional, default False
            Should an empty list of filters the unfiltered list of child nodes, rather
            than filtering out all nodes with any tags? Default False
        """
        ...
    
    @abstractmethod
    def build_input(self, principal: Principal, authn_access_tags: Optional[AccessTags], authn_scopes: Scopes, access_blob: Optional[AccessBlob] = ...) -> str:
        ...
    
    async def init_node(self, principal: Principal, authn_access_tags: Optional[AccessTags], authn_scopes: Scopes, access_blob: Optional[AccessBlob] = ...) -> Tuple[bool, Optional[AccessBlob]]:
        ...
    
    async def modify_node(self, node: BaseAdapter, principal: Principal, authn_access_tags: Optional[AccessTags], authn_scopes: Scopes, access_blob: Optional[AccessBlob]) -> Tuple[bool, Optional[AccessBlob]]:
        ...
    
    async def filters(self, node: BaseAdapter, principal: Principal, authn_access_tags: Optional[AccessTags], authn_scopes: Scopes, scopes: Scopes) -> Filters:
        ...
    
    async def allowed_scopes(self, node: BaseAdapter, principal: Principal, authn_access_tags: Optional[AccessTags], authn_scopes: Scopes) -> Scopes:
        ...
    
