"""
This type stub file was generated by pyright.
"""

import enum
import os
import numpy
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, ClassVar, List, Optional, Tuple, Union
from tiled.structures.root import Structure

FieldDescr = Union[Tuple[str, str], Tuple[str, str, Tuple[int, ...]]]
NumpyDescr = List[FieldDescr]
class Endianness(str, enum.Enum):
    """
    An enum of endian values: big, little, not_applicable.
    """
    big = ...
    little = ...
    not_applicable = ...


class ObjectArrayTypeDisabled(ValueError):
    ...


class Kind(str, enum.Enum):
    """
    See https://numpy.org/devdocs/reference/arrays.interface.html#object.__array_interface__

    The term "kind" comes from the numpy API as well.

    Note: At import time, the environment variable ``TILED_ALLOW_OBJECT_ARRAYS``
    is checked. If it is set to anything other than ``"0"``, then this
    Enum gets an additional member::

        object = "O"

    to support numpy 'object'-type arrays which hold generic Python objects.
    Numpy 'object'-type arrays are not enabled by default because their binary
    representation is not interpretable by clients other than Python.  It is
    recommended to convert your data to a non-object type if possible so that it
    can be read by non-Python clients.
    """
    bit_field = ...
    boolean = ...
    integer = ...
    unsigned_integer = ...
    floating_point = ...
    complex_floating_point = ...
    timedelta = ...
    datetime = ...
    string = ...
    unicode = ...
    other = ...
    if os.getenv("TILED_ALLOW_OBJECT_ARRAYS", "0") != "0":
        object = ...


@dataclass
class BuiltinDtype:
    endianness: Endianness
    kind: Kind
    itemsize: int
    dt_units: Optional[str] = ...
    _endianness_map: ClassVar[Mapping[str, str]] = ...
    _endianness_reverse_map: ClassVar[Mapping[str, str]] = ...
    @classmethod
    def from_numpy_dtype(cls, dtype: numpy.dtype) -> BuiltinDtype:
        ...
    
    def to_numpy_dtype(self) -> numpy.dtype:
        ...
    
    def to_numpy_str(self) -> str:
        ...
    
    def to_numpy_descr(self): # -> str:
        "An alias for to_numpy_str() to match the StructDtype interface."
        ...
    
    @classmethod
    def from_json(cls, structure: Mapping[str, Any]) -> BuiltinDtype:
        ...
    


@dataclass
class Field:
    name: str
    dtype: Union[BuiltinDtype, StructDtype]
    shape: Optional[Tuple[int, ...]]
    @classmethod
    def from_numpy_descr(cls, field: FieldDescr) -> Field:
        ...
    
    def to_numpy_descr(self) -> FieldDescr:
        ...
    
    @classmethod
    def from_json(cls, structure: Mapping[str, Any]) -> Field:
        ...
    


@dataclass
class StructDtype:
    itemsize: int
    fields: List[Field]
    @classmethod
    def from_numpy_dtype(cls, dtype: numpy.dtype) -> StructDtype:
        ...
    
    def to_numpy_dtype(self) -> numpy.dtype:
        ...
    
    def to_numpy_descr(self) -> NumpyDescr:
        ...
    
    def max_depth(self) -> int:
        ...
    
    @classmethod
    def from_json(cls, structure: Mapping[str, Any]) -> StructDtype:
        ...
    


@dataclass
class ArrayStructure(Structure):
    data_type: Union[BuiltinDtype, StructDtype]
    chunks: Tuple[Tuple[int, ...], ...]
    shape: Tuple[int, ...]
    dims: Optional[Tuple[str, ...]] = ...
    resizable: Union[bool, Tuple[bool, ...]] = ...
    @classmethod
    def from_json(cls, structure: Mapping[str, Any]) -> ArrayStructure:
        ...
    
    @classmethod
    def from_array(cls, array, shape=..., chunks=..., dims=...) -> ArrayStructure:
        ...
    
