"""
This type stub file was generated by pyright.
"""

import awkward
from dataclasses import dataclass
from typing import Optional
from tiled.structures.root import Structure

@dataclass
class AwkwardStructure(Structure):
    length: int
    form: dict
    ...


def project_form(form: awkward.forms.Form, form_keys_touched) -> Optional[awkward.forms.Form]:
    ...
