"""
This type stub file was generated by pyright.
"""

import enum
from dataclasses import dataclass
from typing import Dict, Optional
from pydantic import StringConstraints
from typing_extensions import Annotated

"""
This module was created to save structure methods that can be handled by
the server and the client.

"""
class StructureFamily(str, enum.Enum):
    array = ...
    awkward = ...
    container = ...
    sparse = ...
    table = ...


@dataclass(frozen=True)
class Spec:
    name: Annotated[str, StringConstraints(max_length=255)]
    version: Optional[Annotated[str, StringConstraints(max_length=255)]] = ...
    def __init__(self, name, version=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def dict(self) -> Dict[str, Optional[str]]:
        ...
    
    model_dump = ...


STRUCTURE_TYPES = ...
