"""
This type stub file was generated by pyright.
"""

from abc import ABC
from collections.abc import Mapping
from typing import Any

class Structure(ABC):
    @classmethod
    def from_json(cls, structure: Mapping[str, Any]) -> Structure:
        ...
    
