"""
This type stub file was generated by pyright.
"""

import enum
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, Optional, Tuple, Union
from tiled.structures.root import Structure
from .array import BuiltinDtype, StructDtype

class SparseLayout(str, enum.Enum):
    COO = ...


@dataclass
class COOStructure(Structure):
    chunks: Tuple[Tuple[int, ...], ...]
    shape: Tuple[int, ...]
    data_type: Optional[Union[BuiltinDtype, StructDtype]] = ...
    coord_data_type: Optional[BuiltinDtype] = ...
    dims: Optional[Tuple[str, ...]] = ...
    resizable: Union[bool, Tuple[bool, ...]] = ...
    layout: SparseLayout = ...
    @classmethod
    def from_json(cls, structure: Mapping[str, Any]) -> COOStructure:
        ...
    


SparseStructure = COOStructure
