"""
This type stub file was generated by pyright.
"""

import pyarrow
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, List, Tuple, Union
from tiled.structures.root import Structure

B64_ENCODED_PREFIX = ...
@dataclass
class TableStructure(Structure):
    arrow_schema: str
    npartitions: int
    columns: List[str]
    resizable: Union[bool, Tuple[bool, ...]] = ...
    def __post_init__(self): # -> None:
        ...
    
    @classmethod
    def from_dask_dataframe(cls, ddf) -> TableStructure:
        ...
    
    @classmethod
    def from_pandas(cls, df) -> TableStructure:
        ...
    
    @classmethod
    def from_dict(cls, d: Mapping[str, Any]) -> TableStructure:
        ...
    
    @classmethod
    def from_arrays(cls, arr, names: List[str]) -> TableStructure:
        ...
    
    @classmethod
    def from_schema(cls, schema: pyarrow.Schema, npartitions: int = ...) -> TableStructure:
        ...
    
    @classmethod
    def from_arrow_table(cls, table: pyarrow.Table, npartitions: int = ...) -> TableStructure:
        ...
    
    @property
    def arrow_schema_decoded(self) -> pyarrow.Schema:
        ...
    
    @property
    def meta(self):
        ...
    
